### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by werzelrw** [PHPJasper/phpjasper#103]
Hi, I'm having trouble generating the report was working fine but now it gives the following error.
"Mon May 28 12:42:55 BRT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification."

**Comment by geekcom** [comment]
this notice is not related to PHPJasper, please check your connection

**Comment by elton182** [comment]
@geekcom I'v had this same problem, and I found a workaround here: https://cenote-issues.atlassian.net/browse/JAS-116

**Comment by leiviton** [comment]
@elton182 can help me with the solution, I accessed this link but I did not understand how to make useSSL = false in phpjasper, can you help me?

**Comment by hondaman900** [comment]
Did anyone find a resolution to this issue? Adding ?useSSL=false to the URL for the report doesn't fix this. It feels like a database connection issue but the connection works for the Laravel app itself, but not for PHPjasper.

**Comment by hondaman900** [comment]
Well, I resolve this problem by modifying my database host address as follows:

`JASPER_DB_HOST=127.0.0.1&useSSL=false`

but now I get this error, which is completely different and looks more like a Linux issue when the report engine executes:

`(1/1) Exception sh: 1: -n: not found -- in PHPJasper.php line 222`

Any ideas?
