### ISSUE TITLE
report preview

### ISSUE THREAD

**Issue by jorgeescobar** [PHPJasper/phpjasper#106]
good day, I would like to know how to view the pdf in my browser, please

**Comment by geekcom** [comment]
Hi @jorgeescobar, in your report controller can you try something like this?

```php
private function viewReportOnBrowser($output, $extension, $filename)
    {
        header('Content-Description: application/pdf');
        header('Content-Type: application/pdf');
        header('Content-Disposition:; filename=' . $filename . '.' . $extension);
        readfile($output . '.' . $extension);
        unlink(dirname($output) . '/' . $filename . '.' . $extension);
        flush();
        return;
    }`

**Comment by jorgeescobar** [comment]
Thank you very much @geekcom , it worked as follows:

`public function pdfRun()
    {
    	$input = 'C:\xampp\htdocs\phpjasper\vendor\geekcom\phpjasper-laravel\examples\hello_world.jasper';  
		$output = 'C:\xampp\htdocs\phpjasper\vendor\geekcom\phpjasper-laravel\examples';    
		$options = [ 
		    'format' => ['pdf'],
		    'locale' => 'en'
		];

		$jasper = new PHPJasper;

		$rep=$jasper->process(
		    $input,
		    $output,
		    $options
		)->execute();
		$filename='hello_world';
		$extension='pdf';
		$this->viewReportOnBrowser($output, $extension, $filename);
		//return $rep;
	}
	private function viewReportOnBrowser($output, $extension, $filename)
    {
        header('Content-Description: application/pdf');
        header('Content-Type: application/pdf');
        header('Content-Disposition:; filename=' . $filename . '.' . $extension);
        readfile($output . '\\' . $filename . '.' . $extension);
        unlink(dirname($output) . '\examples\\' . $filename . '.' . $extension);
        flush();
        return;
    }`

now the problem is that it takes like 16 or 20 seconds to load

**Comment by geekcom** [comment]
Hi @jorgeescobar, 
about time to load reports please re check your server, generally this action happen in a bit of seconds
