### ISSUE TITLE
Wrong parameter -db-sid

### ISSUE THREAD

**Issue by rlouissidney** [PHPJasper/phpjasper#108]
The parameter should be --db-sid

**Comment by geekcom** [comment]
Please use Java JDK 1.8

**Comment by rlouissidney** [comment]
See here http://jasperstarter.cenote.de/usage.html#The_command_process_pr
I use an oracle database.
The generate code by phpjasper is -db-sid instead --db-sid  ;)
a minor bug bug very annoying.

**Comment by geekcom** [comment]
Yep, sorry @rlouissidney you're right, I will correct it now, thanks

**Comment by geekcom** [comment]
Solved https://github.com/PHPJasper/phpjasper/pull/109
