### ISSUE TITLE
What are the requirements?

### ISSUE THREAD

**Issue by faphdev** [PHPJasper/phpjasper#113]
Sorry if this may sound like a stupid question. Do I need a JasperServer running somewhere? How does it actually work? PHP connects to JasperServer which in turn connects to the DB?

Thanks for clarifying.

**Comment by ajcastro** [comment]
Maybe you need to change the question. I also have the same question in mind, how does this work on php? Does it need a jasper server? Or it just needs the jasper xml file then it will be processed by pure php?

Based on reading the readme doc,. my thinking is that it is just happening inside by pure php.

**Comment by ajcastro** [comment]
https://github.com/PHPJasper/phpjasper/blob/master/src/PHPJasper.php

From reading the source code.. it needs an executable jasperstarter which will handles the generation of report.

**Comment by luisfwermann** [comment]
Hello guys,

The reports are generated on your own server, with Java. More specifically on https://github.com/PHPJasper/phpjasper/blob/master/bin/jasperstarter/bin/jasperstarter where it uses for a .jar library (which is the Jasper Server itself, i think).

You just need the PHP 7.0+ and Java 8. About the database, you can either use JSON to pass data, or you can put the SQL query inside the .jrxml and let the .jar connect to the database and get the records .

Take a look to the documentation on the homepage of the project, there it explains very well how you can use all these features. I would recommend you to download the Jaspersoft Studio (https://community.jaspersoft.com/project/jaspersoft-studio) which is the IDE to design the reports.

**Comment by geekcom** [comment]
Exactly @luisfwermann
