### ISSUE TITLE
Example: report with sub reports using JSON data source

### ISSUE THREAD

**Issue by edersoares** [PHPJasper/phpjasper#114]
We would like an example using JSON as a data source in a report that has one or more sub reports within it and that this data source is passed to its sub reports.

Thanks.

**Comment by geekcom** [comment]
Off course @edersoares, I'll do it as soon as possible.

**Comment by yuzrie** [comment]
any updates on this? in the examples repo, I only see example with Db.. I'm getting the part for subreport blank, while the header and footer shows.. here's an example of what I'm getting with phpjasper.. in jasper studio, it generates just fine

![failed](https://user-images.githubusercontent.com/51981484/82639766-f7a4d600-9c3b-11ea-90cd-48f660698e42.png)

I've tried hardcoding the path in subreport expression and also tried using parameter, both doesn't work.

currently the subreport options are like this

![test](https://user-images.githubusercontent.com/51981484/82639982-5a966d00-9c3c-11ea-8cfa-cdb2783d6d70.PNG)
