### ISSUE TITLE
phpjasper report is not compiling with core php

### ISSUE THREAD

**Issue by fawad0301** [PHPJasper/phpjasper#115]
``// compiling the report 
require 'vendor/autoload.php';

use PHPJasper\PHPJasper;    

$input = 'vendor/geekcom/phpjasper/examples/rptemployees.jasper';   
$output = 'vendor/geekcom/phpjasper/examples/';
$options = [
    'format' => ['pdf'],
    'locale' => 'en',
    'params' => [],
    'db_connection' => [
        'driver' => 'mysql', //mysql, ....
        'username' => 'root',
        'password' => '',
        'host' => 'localhost',
        'database' => 'db_jasper',
        'port' => '1433'
    ]
];

$jasper = new PHPJasper;

$jasper->process(
        $input,
        $output,
        $options
)->execute();

// loading the file

$file = ('vendor/geekcom/phpjasper/examples/rptemployees.pdf');
$filename = ('vendor/geekcom/phpjasper/examples/rptemployees.pdf');
header('Content-type: application/pdf');
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
@readfile($file);

but got an error 

-----
Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and could 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\xampp\htdocs\jreports\vendor\geekcom\phpjasper\src\PHPJasper.php on line 219
----

Really I don't know how to handle this error, I am using 
netbean 8.2,
 java 1.8.1

please help me to complete my all finnacial reportings .

**Comment by danilloabreu** [comment]
Hey!
Sure about the port number ? (not 3306 ?)
Run it on cli and check the output.
windows -> open cmd -> find your folder
then 
php yourfile.php

and check message

good luck!

**Comment by geekcom** [comment]
Closed by inactivity
