### ISSUE TITLE
How To Make In Clause

### ISSUE THREAD

**Issue by freekbass** [PHPJasper/phpjasper#118]
I need to generate an sql, with an in condition, since in source it does not accept array as parameter, how can I proceed?

**Comment by danilloabreu** [comment]
not sure... have you tried add params ?
'params' => [],

Are you using jasperstudio ?

**Comment by geekcom** [comment]
Hi @freekbass PHPJasper accepts array as parameter, please check the examples:
https://github.com/PHPJasper/examples/blob/master/src/Examples.php

**Comment by geekcom** [comment]
Closed by inactivity.
