### ISSUE TITLE
SubReport - Error filling reportResource not found at:

### ISSUE THREAD

**Issue by danilloabreu** [PHPJasper/phpjasper#119]
I have a main report and a subreport working fine in Jaspersoft. (data from mysql)
I'm trying generating a pdf using PHPJasper (geekcom), but I have the following problem:

	Error filling reportResource not found at: subreport.jasper

I assume it's just a problem at this line:

<subreportExpression><![CDATA["subreport.jasper"]]></subreportExpression>

Both reports are at same folder

How to set the path ?

**Comment by thiagospind** [comment]
I'm having the same problem!
