### ISSUE TITLE
Your report has an error and couldn 't be processed!

### ISSUE THREAD

**Issue by PauloCSto** [PHPJasper/phpjasper#120]
Estou começando a estudar o phpjasper, fiz os testes conforme as instruções, estava dando tudo certo, mas quando comecei testar a conexão com meu banco de dados (mysql) tive um problema que ainda não consegui resolver e passou a dar o seguinte erro:

**"Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\xampp\htdocs\jasper\vendor\geekcom\phpjasper\src\PHPJasper.php:219 Stack trace: #0 C:\xampp\htdocs\jasper\teste2.php(30): PHPJasper\PHPJasper->execute() #1 {main} thrown in C:\xampp\htdocs\jasper\vendor\geekcom\phpjasper\src\PHPJasper.php on line 219"**

meu código : 
``

> 

`<?php
require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;

$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/convenio.jasper';  
$output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    

$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => [],
    'db_connection' => [
        'driver' => 'mysql',
        'username' => 'root',
        'password' => '',
        'host' => 'localhost',
        'database' => 'labordb',
        'port' => '3306'
    ]
];

$jasper = new PHPJasper;

 $jasper->process($input,$output,$options)->execute();
`

 Mudei a linha para:

> `echo $jasper->process($input,$output,$options)->output();`

> apareceu a seguinte mensagem:

 jasperstarter --locale pt_BR process "C:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples/convenio.jasper" -o "C:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples" -f pdf -t mysql -u root -p -H localhost -n labordb --db-port 3306

**Comment by PauloCSto** [comment]
Se alguém ja conseguiu resolver e puder me ajudar eu agradeço.

**Comment by PauloCSto** [comment]
Se alguém pude me ajudar eu agradeço.

**Comment by geekcom** [comment]
Ola @PauloCSto  obrigado por apoiar a lib, faça o seguinte:

1. Abra seu terminal ou cmd
2. Navegue até a pasta  **.../bin/jasperstarter/bin** que é onde fica o executável da lib
3. Cole o resultado aqui para ajudarmos você

Comando a ser executado:

`jasperstarter --locale pt_BR process "C:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples/convenio.jasper" -o "C:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples" -f pdf -t mysql -u root -p -H localhost -n labordb --db-port 3306`

**Comment by PauloCSto** [comment]
Executei a linha de comando e apresentou o seguinte resultado:



C:\xampp\htdocs\jasper\vendor\geekcom\phpjasper\bin\jasperstarter\bin>jasperstarter
--locale pt_BR porcess
"c:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples/convenio.jasper"
-o "c:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples" -f pdf -t
mysql-u root -p -H localhost -n labordb --db-port 3306
usage: jasperstarter [-h] [--locale <lang>] [-v] [-V] <cmd> ...
jasperstarter: error: invalid  choice:  'porcess'  (choose  from 'compile',
'cp',    'process',    'pr',     'list_printers',     'printers',    'lpr',
'list_parameters', 'params', 'lpa')

Did you mean:
        process

C:\xampp\htdocs\jasper\vendor\geekcom\phpjasper\bin\jasperstarter\bin>

Em ter, 23 de out de 2018 às 09:35, Daniel Rodrigues <
notifications@github.com> escreveu:

**Comment by geekcom** [comment]
@PauloCSto confira novamente o seu arquivo principal, de acordo com o erro o problema  é que você está tentando executar o comando "porcess", o correto é "process"

**Comment by PauloCSto** [comment]
Desculpe, ficou assim agora:

\xampp\htdocs\jasper\vendor\geekcom\phpjasper\bin\jasperstarter\bin>jasperstarter
> --locale pt_BR process
> "c:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples/convenio.jasper"
> -o "c:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples" -f pdf -t
> mysql -u root -p -H localhost -n labordb --db-port 3306
> usage: jasperstarter process [-h] -f <fmt> [<fmt> ...] [-o <output>] [-w]
>                      [-a [<filter>]] [-P <param> [<param> ...]]
>                      [-r [<resource>]] [-t <dstype>] [-H <dbhost>]
>                      [-u <dbuser>] [-p <dbpasswd>] [-n <dbname>]
>                      [--db-sid <sid>] [--db-port <port>]
>                      [--db-driver <name>] [--db-url <jdbcUrl>]
>                      [--jdbc-dir <dir>] [--data-file <file>]
>                      [--csv-first-row] [--csv-columns <list>]
>                      [--csv-record-del <delimiter>]
>                      [--csv-field-del <delimiter>]
>                      [--csv-charset <charset>] [--xml-xpath <xpath>]
>                      [--json-query <jsonquery>] [-N <printername>] [-d]
>                      [-s <reportname>] [-c <copies>]
>                      [--out-field-del <delimiter>]
>                      [--out-charset <charset>] <input>
>>
>> jasperstarter: error: argument -p: expected one argument
>>
>

----------------------------------------------------------------------------------------------------------------------------------

**Comment by PauloCSto** [comment]
agora eu retirei o -p da linha de comando, apareceu assim:



> C:\xampp\htdocs\jasper\vendor\geekcom\phpjasper\bin\jasperstarter\bin>jasperstarter
> --locale pt_BR process
> "c:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples/convenio.jasper"
> -o "c:\xampp\htdocs\jasper/vendor/geekcom/phpjasper/examples" -f pdf -t
> mysql -u root -H localhost -n labordb --db-port 3306
> Error filling reportByte data not found at: leaf_banner_gray.png.
>

-------------------------------------------------------------------------------------------------------------------------
o que significa o parâmetro -p na mensagem?

**Comment by PauloCSto** [comment]
Graças à sua ajuda, conseguimos resolver:

retirei o parâmetro 'password', pois não coloquei senha para acessar o banco;
depois seguindo a sua orientação, veriiquei que a imagem .png não estava na pasta correta.

Deu certo.

meu prôximo passo agora é fazer testes em um dominio no servidor da web.

Muito Obrigado.

**Comment by PauloCSto** [comment]
ficou assim  👍 

require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;

$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/convenio.jasper';  
$output = __DIR__ . '/vendor/geekcom/phpjasper/examples';  


$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => [],
    'db_connection' => [
        'driver' => 'mysql',
        'username' => 'root',
        'host' => 'localhost',
        'database' => 'labordb',
        'port' => '3306'
    ]
];


$jasper = new PHPJasper;
 $jasper->process($input,$output,$options)->execute();


$file = $output .'/convenio.pdf';
$filename = 'Faturamento'; 

header('Content-type: application/pdf');
header('Content-Disposition: inline; filename="' . $filename . '"');
header('Content-Transfer-Encoding: binary');
header('Content-Length: ' . filesize($file));
header('Accept-Ranges: bytes');

@readfile($file);

**Comment by geekcom** [comment]
Se verificar algum problema por favor abra outra issue, que bom que está rodando como esperado, abs.
