### ISSUE TITLE
Turkish characters wrong typing

### ISSUE THREAD

**Issue by canerd7u** [PHPJasper/phpjasper#122]
im using mysql database connection and i have turkish string values. but my pdf file in changes " ı , Ş" charcters to "?". how to fix it. ?

**Comment by geekcom** [comment]
Hi @CanerDumanoglu thanks for use PHPJasper, to solve your problem you need to pass one more parameter, `'locale' => 'tr'` please see the example below:

For a complete list of locales see [Supported Locales](https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html)

```php
$options = [
    'format' => ['pdf'],
    'locale' => 'tr',
    'params' => [],
    'db_connection' => [
        'driver' => 'postgres', //mysql, ....
        'username' => 'DB_USERNAME',
        'password' => 'DB_PASSWORD',
        'host' => 'DB_HOST',
        'database' => 'DB_DATABASE',
        'port' => '5432'
    ]
];

**Comment by CanerDumanoglu** [comment]
thank you @geekcom ;

i have now another problem my error message : 

> Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\laragon\www\jasper\vendor\geekcom\phpjasper\src\PHPJasper.php:219 Stack trace: #0 C:\laragon\www\jasper\compile.php(28): PHPJasper\PHPJasper->execute() #1 {main} thrown in C:\laragon\www\jasper\vendor\geekcom\phpjasper\src\PHPJasper.php on line 219

my code 

`require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;

$input = '/Blank_A4.jasper';
$output = '/';
$options = [
    'format' => ['pdf'],
    'locale' => 'tr',
    'params' => [],
    'db_connection' => [
        'driver' => 'mysql', //mysql, ....
        'username' => 'root',
        'password' => '',
        'host' => 'localhost',
        'database' => '00001'
    ]
];

$jasper = new PHPJasper;

$jasper->process(
    $input,
    $output,
    $options
)->execute();`

**Comment by canerd7u** [comment]
thank you @geekcom for answer.

İ am using your answer codes but not working my turkish character ' ı ' now removed in pdf. İ use  Jaspersoft studio in prewiev and see türkish characters working. only now not working in code with make pdf

--EDİT

i will save pdf in jaspersoft studio and open file same turkish characters removed.

**Comment by geekcom** [comment]
Closed by inactivity
