### ISSUE TITLE
Report null fields on laravel PHPJasper

### ISSUE THREAD

**Issue by devpaulopaixao** [PHPJasper/phpjasper#125]

**Comment by blackswitch09** [comment]
Geekcom, estou à alguns dias garimpando pelas issues pra tentar encontrar uma solução para o meu problema mas não encontro.
Poderia me ajudar?
Estou usando o lavela/phpjasper e já tentei com alguns outros..minha controller está assim:

<?php
namespace App\Http\Controllers;

use PHPJasper\PHPJasper;

class ReportController extends Controller
{
    public function getDatabaseConfig()
    {
        return [
            'driver' => env('DB_CONNECTION'),
            'host' => env('DB_HOST'),
            'port' => env('DB_PORT'),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'jdbc_dir' => base_path() . env('JDBC_DIR'),
        ];
    }

    public function index()
    {

        $jdbc_dir = __DIR__ . '/vendor/lavela/phpjasper/bin/jaspertarter/jdbc';

        $input = public_path() . '/report/Customers.jasper';

        $output = public_path() . '/report/' . time() . '_ordemServico';

        /*$options = [
        'format' => ['pdf'],
        'locale' => 'en',
        'params' => []
        ];*/

        $options = [
            'format' => ['pdf'],
            'locale' => 'pt_BR',
            'params' => [],
            $this->getDatabaseConfig()
        ];

        

        $report = new PHPJasper;

        $report->process(
            $input,
            $output//,
            //$options
        )->execute();

        //dd($report);

        $file = $output . '.pdf';
        $path = $file;

        if (!file_exists($file)) {
            abort(404);
        }

        $file = file_get_contents($file);

        unlink($path);

        return response($file, 200)
            ->header('Content-Type', 'application/pdf')
            ->header('Content-Disposition', 'inline; filename="_ordemServico.pdf"');
    }
}

**Comment by devpaulopaixao** [comment]
Geekcom, estou à alguns dias garimpando pelas issues pra tentar encontrar uma solução para o meu problema mas não encontro.
Poderia me ajudar?
Estou usando o lavela/phpjasper e já tentei com alguns outros..minha controller está assim:

![image](https://user-images.githubusercontent.com/37369648/48099966-8f80d180-e208-11e8-8e88-4eeb13b7b181.png)

**Comment by devpaulopaixao** [comment]
o arquivo customers está configurado para buscar dados de uma tabela com o mesmo nome na base de dados

**Comment by geekcom** [comment]
Olá @blackswitch09 tente usar esta lib ao invés de lavela;phpjasper, tem bastante coisa diferente, ou então abre uma issue por lá.

**Comment by devpaulopaixao** [comment]
Obrigado pelo feedback;
Consegui resolver o problema dando um downgrade da versão para a versão 2 do lavela/Jasper;
Por algum motivo desconhecido, tanto a versão 3 do lavela quanto a ultima do PHPJasper estavam dando o mesmo erro..
