### ISSUE TITLE
erro ao conectar com banco de dados MYSQL - Windows10

### ISSUE THREAD

**Issue by ivanfsilva** [PHPJasper/phpjasper#126]
Olá,

Estou usando o PHP 7.2.9 e nenhum framework como Laravel.

Quando eu executo o script PHP sem a conexão ao BD, o relatório é executado normalmente. Quando eu coloco a conexão do BD, dá o seguinte erro:

> Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\xampp\htdocs\PortPar\vendor\geekcom\phpjasper\src\PHPJasper.php:219 Stack trace: #0 C:\xampp\htdocs\PortPar\views\relContasBancariasPorEmpresa.php(48): PHPJasper\PHPJasper->execute() #1 C:\xampp\htdocs\PortPar\core\controller.php(13): require('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\PortPar\controllers\contasBancariasController.php(120): controller->loadView('relContasBancar...', Array) #3 C:\xampp\htdocs\PortPar\core\Core.php(43): contasBancariasController->relContasBancariasPorEmpresa() #4 C:\xampp\htdocs\PortPar\index.php(30): Core->run() #5 {main} thrown in C:\xampp\htdocs\PortPar\vendor\geekcom\phpjasper\src\PHPJasper.php on line 219

### Uma pergunta: baixando o conector mysql, preciso copiá-lo para alguma pasta específica no XAMPP ?

**SEGUE o SCRIPT PHP:**

`<?php 

    use PHPJasper\PHPJasper;

    $input = '\\xampp\htdocs\PortPar\rel\relContasBancarias.jasper';  
    $output = '\\xampp\htdocs\PortPar\rel';    
    $options = [
        'format' => ['pdf'],
        'locale' => 'pt_BR',
        'params' => [],
        'db_connection' => [
            'driver' => 'mysql',
            'username' => 'root',
            'password' => '',
            'host' => 'localhost',
            'database' => 'sdp',
            'port' => '3306'
        ]
    ];

    $jasper = new PHPJasper;

    $jasper->process(
        $input,
        $output,
        $options
    )->execute();

    // loading the file

    $file = ('\\xampp\htdocs\PortPar\rel\relContasBancarias.pdf');
    $filename = ('\\xampp\htdocs\PortPar\rel\relContasBancarias.pdf');
    header('Content-type: application/pdf');
    header('Content-Transfer-Encoding: binary');
    header('Accept-Ranges: bytes');
    @readfile($file);

?>`

Obrigado!

**Comment by geekcom** [comment]
Olá @ivanfsilva verifica os dados da sua conexão, o driver JDBC para MySQL já está dentro da pasta **phpjasper/bin/jasperstarter/jdbc/**

**Comment by ivanfsilva** [comment]
Olá Daniel,

> 'db_connection' => [
        'driver' => 'mysql',
        'username' => 'root',
        'password' => '',
        'host' => 'localhost',
        'database' => 'sdp',
        'port' => '3306'
    ]

Mas essa estrutura dos parâmetros da conexão estão corretos? Referente ao 'host', basta colocar localhost ou preciso informar todo o caminho até chegar a pasta onde está localizado o banco no xampp?
o parâmetro 'driver' também está correto para especificar o mysql?

Obrigado!

**Comment by geekcom** [comment]
A forma de escrever os parâmetros estão corretas, driver também está ok, o que você precisa passar aí são as mesmas informações que você passaria para se conectar usando um gerenciador de banco qualquer a exemplo do MySQL WorkBench, tenta gerar a saída do comando usando o método output() assim:
```php
print $jasper->process(
    $input,
    $output,
    $options
)->output();
```
Então copia esse o comando gerado e executa no terminal dentro da pasta: 
`phpjasper/bin/jasperstarter/bin/`, que é onde fica o arquivo executável da lib, então observe o retorno, assim você vai achar o erro, se quiser pode colar o retorno aqui pra tentarmos te ajudar.

**Comment by ivanfsilva** [comment]
Olá Daniel,

uma pergunta: Posso setar o relatório no Jasper studio para utilizar como fonte de dados um array em memória? Se eu puder imprimir o conteúdo de um array, não precisaria mais de conexão do banco através do relatório, pois faria isso pela aplicação e a aplicação mandaria o array com as informações para impressão... 

Obrigado!

**Comment by geekcom** [comment]
@ivanfsilva  nunca tentei dessa forma, seria interessante você tentar

**Comment by geekcom** [comment]
@ivanfsilva se a questão foi resolvida peço que feche a issue
