### ISSUE TITLE
Font change generating PDF

### ISSUE THREAD

**Issue by donbraz** [PHPJasper/phpjasper#127]
With JasperSoft generated report in Times New Roman font. When generating in JasperSoft then whole document is generating good. But when I copy report to system and generating document to PDF over console then font changes and no bold or italic fonts.

**Comment by geekcom** [comment]
Hi @donbraz check if your font is installed in your OS

**Comment by donbraz** [comment]
> Hi @donbraz check if your font is installed in your OS

I checked and Times New Roman font is installed in OS.

**Comment by obinakiller** [comment]
Eu também tenho este mesmo problema. O pdf gerado não inclui as alterações, como negrito, itálico, mesmo as mesmas sendo configuradas no arquivo jasper.

I also have this same problem. The generated pdf does not include the changes, like bold, italic, even the same ones being configured in the jasper file.

**Comment by geekcom** [comment]
Closed for inactivity
