### ISSUE TITLE
How can I install jasperPHP without using composer?

### ISSUE THREAD

**Issue by wired777b** [PHPJasper/phpjasper#132]
is there a way to install this library manually without using php composer? I just need to use this to generate some reports in godaddy hosted php application where it's not possible to install php composer

**Comment by geekcom** [comment]
@khaled777b Caramba, impressionante alguém perguntar isso

**Comment by geekcom** [comment]
Hi @khaled777b just copy the folder` /vendor` to the root of your project this folder is generated when you run the `composer install`

**Comment by wired777b** [comment]
Thank you. This is my first php application and that was helpful

**Comment by faiztriguna** [comment]
Hi @geekcom , why can't I have  /vendor/geekcom even after run > composer ?
I've create an issue regarding this matter. Pls help....
