### ISSUE TITLE
conexão banco mysql

### ISSUE THREAD

**Issue by lopemede** [PHPJasper/phpjasper#14]
Boa tarde, 
fiz todos os procedimentos de  instalação e esta rodando tudo ok, porém ao utilizar o exemplo com conexão ao banco de dados esta apresentando erros de syntaxe no PHP, poderia passar um exemplo de conexão com banco MySql?

**Comment by geekcom** [comment]
Olá @lopemede, obrigado por abrir essa issue, sim claro vou verificar em algumas horas envio um exemplo pra você.

**Comment by geekcom** [comment]
É mais ou menos isso que você precisa.

```
 require __DIR__ . '/vendor/autoload.php';

 use JasperPHP\JasperPHP;

 $input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jrxml';
 $output = __DIR__ . '/vendor/geekcom/phpjasper/examples';


 $conn = [
     'driver' => 'mysql',
     'username' => 'root',
     'password' => '123456',
     'host' => 'localhost',
     'database' => 'report',
     'port' => '3306'
 ];

 $jasper = new JasperPHP;

 $jasper->process(
     $input,
     $output,
     array("pdf", "rtf"),
     array("php_version" => phpversion()),
     $conn,
     true,
     true,
     'pt_BR' //LOCALE *note 2
 )->execute();`
```

**Comment by geekcom** [comment]
Você esta usando laravel?

**Comment by lopemede** [comment]
Bom dia, 
Obrigado pela dica, 
laravel, não estou usando não...

**Comment by lopemede** [comment]
Vou tentar aqui , qualquer novidade retorno...
valeu!

**Comment by lopemede** [comment]
Boa tarde @geekcom,
Fiz os procedimentos, mas qdo rodo pelo browser apresenta o erro:
Fatal error: Uncaught exception 'Exception' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.' in .

rodando pelo terminal(linux) com a opção 'execute', gera normalmente o relatorio PDF no diretorio especificado. A opção output não faz nada, em branco no browser e no terminal não apresenta nada
falta algum parametro para abrir pelo browser?

**Comment by geekcom** [comment]
Bom dia @lopemede , verifica se o java ta rodando legal, a variavél **output** é exatamente onde será gerado o seu relatório.

**Comment by lopemede** [comment]
Boa tarde @geekcom , primeiramente obrigado pelas dicas...
então meu java esta normal:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

meu código para geração do relatório:

```
require __DIR__ . '/phpjasper-master/vendor/autoload.php';

//ini_set('display_errors', 0);

use JasperPHP\JasperPHP;

$input = __DIR__ . '/forn_cli.jasper';
$output = __DIR__ . '/tmp/';

$conn = [
    'driver' => 'mysql',
    'username' => 'root',
    'password' => '',
    'host' => 'localhost',
    'database' => 'banco',
    'port' => '3306'
];


$jasper = new JasperPHP;
$jasper->process(
        $input,
        $output,
        array("pdf"),
        array(),
        $conn,
        true,
        true,
        'pt_BR' //LOCALE *note 2
)->execute();
```

O estranho que gerando pelo navegador apresenta o erro: 

"Fatal error: Uncaught exception 'Exception' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.' in /opt/lampp/htdocs/projeto/includes/reports/phpjasper-master/vendor/geekcom/phpjasper/src/JasperPHP/JasperPHP.php:197 Stack trace: #0 /opt/lampp/htdocs/projeto/includes/reports/relatorio.php(34): JasperPHP\JasperPHP->execute() #1 {main} thrown in /opt/lampp/htdocs/projeto/includes/reports/phpjasper-master/vendor/geekcom/phpjasper/src/JasperPHP/JasperPHP.php on line 197.

Mas quando executo pelo terminal usando o comando: 
php relatorio.php

Ele gera normalmente o arquivo PDF no diretorio TMP como no código e sem mensagens de erro...

Estou usando um ambiente com XAMPP, PHP 5.5.9

Obs: com o arquivo do exemplo(example.php / hello_word.jasper) , acontece mesma coisa

**Comment by geekcom** [comment]
Desculpe não ter respondido ainda @lopemede , ando meio atarefado, vou tentar resolver esse fim de semana, caso você ainda não tenha solucionado

**Comment by lopemede** [comment]
Bom dia @geekcom , ok sem problemas...
Estou analisando aqui também vendo se acho o que pode ser o problema... 
qualquer novidade lhe informo...

valeu!

**Comment by lopemede** [comment]
Boa noite @geekcom , com muito custo e debugando o código(rsrs) consegui encontrar o problema, 
Estava no server linux , problema no java erro "java.lang.InternalError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
   at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)"  ao passar o comando e por isso não gerava no localhost(browser).
Fiz algumas alterações nas permissões do xhost e esta rolando perfeitamente...
Vou continuar os testes na classe, qualquer novidade te falo...
Obrigado pelas dicas...

Até +

**Comment by geekcom** [comment]
Você ter respondido a issue foi muito valioso pra comunidade que usa a lib, muito obrigado.

---

De: João Paulo Medeiros notifications@github.com
Enviado: segunda-feira, 21 de novembro de 2016 18:05:50
Para: geekcom/phpjasper
Cc: Daniel Rodrigues Lima; Mention
Assunto: Re: [geekcom/phpjasper] conexão banco mysql (#14)

Boa noite @geekcomhttps://github.com/geekcom , com muito custo e debugando o código(rsrs) consegui encontrar o problema,
Estava no server linux , problema no java erro "java.lang.InternalError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)" ao passar o comando e por isso não gerava no localhost(browser).
Fiz algumas alterações nas permissões do xhost e esta rolando perfeitamente...
Vou continuar os testes na classe, qualquer novidade te falo...
Obrigado pelas dicas...

Até +

##
