### ISSUE TITLE
Can not install geekcom/phpjasper via composer

### ISSUE THREAD

**Issue by faiztriguna** [PHPJasper/phpjasper#141]
**Describe the bug**
I could not install package geekcom/phpjasper via composer, either via "editing composer.json and run: composer install" nor via "composer require geekcom/phpjasper".

I run in :
- Windows 7 Professional
- Latest Chrome browser
- Java 1.8
- XAMPP for Windows 7.1.27
- PHP Version 7.1.27
- Composer with latest version (after PHP 7.1.27 installed)

Please anyone can help me what I was do wrong ? Or did I miss something, maybe I need to install another plugins/programs ?

Any suggestion would be appreciated.

Thank you in advance..

![jasper-01](https://user-images.githubusercontent.com/47574776/55595100-786cee00-576c-11e9-9858-3787a25fe466.JPG)
![jasper-02](https://user-images.githubusercontent.com/47574776/55595103-7c990b80-576c-11e9-9138-3587de676ced.JPG)

**Comment by geekcom** [comment]
Hi @faiztriguna remove the line you wrote on your composer.json and tr again.
