### ISSUE TITLE
Does PHPJasper support JPA Connection?

### ISSUE THREAD

**Issue by freebornforever** [PHPJasper/phpjasper#147]
**Is your feature request related to a problem? Please describe.**
JPA is widely used and it is easy for developer.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geekcom** [comment]
@freebornforever Yes

**Comment by freebornforever** [comment]
> @freebornforever Yes
I didn't find any example yet.
How to use JPA Connection?
or let me know where I can get the example.

**Comment by geekcom** [comment]
> > @freebornforever Yes
> > I didn't find any example yet.
> > How to use JPA Connection?
> > or let me know where I can get the example.

There are many discussion about this [here](https://community.jaspersoft.com/questions/1046671/jaspersoft-connection-mysql-db)
