### ISSUE TITLE
Report returning null

### ISSUE THREAD

**Issue by dev-gustaavo** [PHPJasper/phpjasper#149]
**Relatório retornando null**
Montei um relatório simples para começar a utilizar a biblioteca PHPJasper, fiz todas as conexões necessárias no JasperStudio e por lá consegui conectar com a base de dados e retornar os dados na aba preview normalmente. No entanto, quando faço a implementação do código, o relatório exibido não retorna os dados, vem somente com a informação **null**.

Conforme exibido abaixo:

![image](https://user-images.githubusercontent.com/19441895/58138802-46292a00-7c0e-11e9-80ce-582ec01bea16.png)

Para chegar até o relatório, tenho os seguintes métodos:

public function getDatabaseConfig()
	{
		return [
			'format' => ['pdf'],
			'locale' => 'pt-BR',
			'params' => [],
			'db_connection' => [
				'driver' => 'mysql', //mysql, ....
				'username' => env('DB_USERNAME'),
				'password' => env('DB_PASSWORD'),
				'host' => env('DB_HOST'),
				'database' => env('DB_DATABASE'),
				'port' => env('DB_PORT')
				]
			];
	}

public function jasper() {
    	$output = public_path() . '/reports/' . time() . '_teste';
	
	    $report = new PHPJasper();
		
	    $report->process(
		    public_path() . '/reports/teste_relatorio.jrxml',
		    $output,
		    ['pdf'],
		    [],
		    $this->getDatabaseConfig()
	    )->execute();
	    $file = $output . '.pdf';
	    $path = $file;
	
	    if (!file_exists($file)) {
		    abort(404);
	    }
	    
		$file = file_get_contents($file);
	    
		unlink($path);
	    
		return response($file, 200)
		    ->header('Content-Type', 'application/pdf')
		    ->header('Content-Disposition', 'inline; filename="teste_relatorio.pdf"');
	
    }

**Comment by geekcom** [comment]
Tente conferir a conexão com o banco de dados.

**Comment by dev-gustaavo** [comment]
A conexão da aplicação está ok. Quando faço essa chamada via Jasper Studio, também está ok, o problema ocorre somente no momento de chamar via aplicação.

**Comment by geekcom** [comment]
@DeveloperGustavo  resolveu o problema?

**Comment by dev-gustaavo** [comment]
Sim, resolvido. Obrigado.

**Comment by douglas-moreno** [comment]
@dev-gustaavo Como vc resolveu esse problema? Estou quebrando a cabeça aqui e ainda não encontrei uma solução!
O relatório no Jaspersoft Studio conecta no banco e traz as informações, mas não na aplicação.
Agradeço qualquer ajuda!
