### ISSUE TITLE
Jasper report pdf export issue with mysql db connection

### ISSUE THREAD

**Issue by sfdsfdsfdesfdsghefasefs** [PHPJasper/phpjasper#151]
**Getting error like**
>>>Exception: usage:  uses : jasperstarter process [-h] -f [<fmt>...] [-o <output>] [-w]

How can solve it 
Its generate if i pass db_connection array key from $params array.

Please help me.
Thanks :)

**Comment by geekcom** [comment]
Please follow the docs.
