### ISSUE TITLE
geekcom/phpjasper via composer install succes but composer update having issue

### ISSUE THREAD

**Issue by jazi3652** [PHPJasper/phpjasper#153]
geekcom/phpjasper via composer install success but composer cannot update i am using laravel 5.8 and php version 7.2.4 .tell me the issue .See screen shot  below
![Capture](https://user-images.githubusercontent.com/52414443/60441291-22ef9280-9c30-11e9-9676-1a7bbddf5ac1.PNG)

**Comment by geekcom** [comment]
Plase follow the instructions to install and use PHPJasper.

**Comment by jazi3652** [comment]
Again i am try and follow the instruction to install but facing this error again
