### ISSUE TITLE
JDK

### ISSUE THREAD

**Issue by wiltonbarros** [PHPJasper/phpjasper#155]
@geekcom, localmente meus reports funcionam perfeitamente, inclusive enviando parâmetros.
Quando subo para a hospedagem compartilhada do hostgator, gera a mensagem:

Uncaught Error: Class 'PHPJasper\PHPJasper' not found in /home/.../public_html/patrimonio.php:93

Enfim, meu composer está em: /home/.../composer
O arquivo patrimonio.php na linha 93 é a chamada $jasper = new PHPJasper;
Outra dúvida é a seguinte, conversando com o suporte da hostgator, eles não possuem jdk instalado, se eu enviar o arquivo já convertido em .jasper ainda necessita do java para gerar o relatório?

Obrigado!

**Comment by geekcom** [comment]
Olá @wiltonbarros, será necessário mesmo ter o JDK instalado no servidor.

**Comment by wiltonbarros** [comment]
@geekcom, normalmente qual hospedagem possui os requisitos?
Obrigado!
