### ISSUE TITLE
Laravel 5.8 install issue

### ISSUE THREAD

**Issue by jazi3652** [PHPJasper/phpjasper#156]
Hi i am trying to install in laravel 5.8 version but i am facing this error 
![Capture](https://user-images.githubusercontent.com/52414443/61233694-92927100-a74a-11e9-933f-d7c9cbd6ee74.PNG)

**Comment by geekcom** [comment]
Please follow the instructions to install.

**Comment by jazi3652** [comment]
You can share me the instruction because i am already follow the instruction ???

**Comment by geekcom** [comment]
Hi @jazi3652 PHPJasper is framework independent.
