### ISSUE TITLE
Rodar output();

### ISSUE THREAD

**Issue by wiltonbarros** [PHPJasper/phpjasper#157]
@geekcom, como faço para rodar o output(); no console para verificar o erro que está gerando?
Obrigado!

**Comment by wiltonbarros** [comment]
Estou rodando em um Centos 7.

**Comment by wiltonbarros** [comment]
Boa tarde!
Rodando o exemplo ou relatório que montei (conecta com o banco), gera o print em anexo.
![erro jasperphp](https://user-images.githubusercontent.com/23128619/61583910-59c11600-ab15-11e9-81ce-ea4aced2f139.PNG)

**Comment by wiltonbarros** [comment]
Quando eu rodo pelo bash o comando abaixo gera o arquivo.
![print vps](https://user-images.githubusercontent.com/23128619/61585413-7f5c1880-ab31-11e9-9400-0b2000eb8031.PNG)

Quando tento gerar pelo php gera o código:
/jasperstarter process "/composer/vendor/geekcom/phpjasper/examples/hello_world.jasper" -o "/var/www/html/composer/vendor/geekcom/phpjasper/examples/" -f pdf
Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /var/www/html/composer/vendor/geekcom/phpjasper/src/PHPJasper.php:219 Stack trace: #0 /var/www/html/redirect.php(56): PHPJasper\PHPJasper->execute() #1 {main} thrown in /var/www/html/composer/vendor/geekcom/phpjasper/src/PHPJasper.php on line 219"

**Comment by LeafarDev** [comment]
Tive o mesmo problema, era permissão, você precisa dar permissão para usuário do apache(ou derivados) para escrever no diretório do seu projeto. No bash está funcionando pois você está como root.

**Comment by wiltonbarros** [comment]
@LeafarDev Boa tarde!
Você deu permissão total para o usuário do apache?

**Comment by LeafarDev** [comment]
Eu utilizei o chown para deixar o apache como dono da pasta

**Comment by wiltonbarros** [comment]
@LeafarDev Tem um exemplo ai de como você fez?

**Comment by LeafarDev** [comment]
sudo chown -R www-data:www-data /diretorio/do/seu/projeto

**Comment by wiltonbarros** [comment]
@LeafarDev Executei, restartei o httpd, mas ainda continua aparecendo a mensagem.

**Comment by LeafarDev** [comment]
roda ls -l /diretorio/do/seu/projeto e posta aqui

**Comment by wiltonbarros** [comment]
![image](https://user-images.githubusercontent.com/23128619/61651966-5ea8d580-ac8d-11e9-91d8-030f0c565f24.png)

**Comment by wiltonbarros** [comment]
@LeafarDev Aparentemente está com todas as permissões.

**Comment by wiltonbarros** [comment]
Pode ser que meu problema esteja relacionado com a issue#62, vou tentar validar.

**Comment by LeafarDev** [comment]
@wiltonbarros  ah sim, sem permissão para executar o java ? Se não é problema com java ou de permissão, então não sei hehe

**Comment by wiltonbarros** [comment]
@LeafarDev estou pensando em um jeito de dar permissão para o Java, tem ideia de como dar permissão para execução do openjdk em qualquer diretório do sistema?
Já procurei bastante aqui, mas nada conclusivo.

**Comment by LeafarDev** [comment]
@wiltonbarros  não sei se é melhor prática mas você pode tentar algo como 

> sudo chmod +x /usr/bin/java

**Comment by wiltonbarros** [comment]
@LeafarDev  ainda não funcionou, mas estou atrás da questão do java.
Obrigado!

**Comment by wiltonbarros** [comment]
Como será que consigo mostrar o erro que está gerando ao invés da mensagem que mostra no navegador?

**Comment by LeafarDev** [comment]
Tente rodar o comando do output() como o usuário do apache :

> su -s /bin/bash www-data(acho que no seu caso "apache" mesmo)

e depois:

> ./jasperstarter process ...

**Comment by wiltonbarros** [comment]
@LeafarDev  exatamente, é permissão mesmo! Só que eu já havia liberado as permissões para o usuário apache.

![image](https://user-images.githubusercontent.com/23128619/61710200-6ddc6180-ad27-11e9-8c84-3b138669b4c4.png)

**Comment by wiltonbarros** [comment]
@LeafarDev Sabe como resolver isto?

**Comment by wiltonbarros** [comment]
Achei o problema, é o SELinux.
Setando setenforce 0 para teste funciona.
Agora preciso verificar como dar permissão para o apache.

**Comment by geekcom** [comment]
> @LeafarDev exatamente, é permissão mesmo! Só que eu já havia liberado as permissões para o usuário apache.
> 
> ![image](https://user-images.githubusercontent.com/23128619/61710200-6ddc6180-ad27-11e9-8c84-3b138669b4c4.png)

Cara basta você fornecer permissão para o arquivo executável por exemplo:
`sudo chmod 777 ./jasperstarter`

**Comment by wiltonbarros** [comment]
@LeafarDev , @geekcom obrigado pela ajuda!!
Agora está rodando.

**Comment by ghost** [comment]
Show.
