### ISSUE TITLE
Erro gerar relatório com parametros

### ISSUE THREAD

**Issue by wiltonbarros** [PHPJasper/phpjasper#159]
Boa noite!
Estou com dificuldade para gerar relatórios com mais de 1 parâmetro, a mensagem é a seguinte:
input file: "/home/wbtech/public_html/composer/vendor/geekcom/phpjasper/examples/Patrimonio.jasper" is not a valid jrxml file

Quando gero com apenas 1 parametro, a consulta fica conforme abaixo:

select * from patrimonio where cod_empresa =$P{Empresa}

Utilizo: 'params' => ['Empresa' => $empresa]

Quando tento passar mais de 1 parâmetro conforme: select * from patrimonio where cod_empresa =$P{Empresa} and centro_custo in($P{Centro_custo})

'locale' => 'pt_BR',
'params' => ['Empresa' => $empresa,
	      'Centro_custo' =>$filtro
	      ],

Gera o erro que informei acima, no jaspersoft o relatório compila perfeitamente, inclusive, a intensão inicial era gerar um relatório com parametro SQL utilizando: $P!{Filtros}.
Gera o mesmo erro.

Alguém consegue me ajudar?

Obrigado!

**Comment by wiltonbarros** [comment]
Resolvido!

**Comment by geekcom** [comment]
Qual foi o problema @wiltonbarros, qando resolve é bom compartilhar, assim a comunidade aprende.
