### ISSUE TITLE
Change Generated PDF TItle

### ISSUE THREAD

**Issue by Karacraft** [PHPJasper/phpjasper#160]
I was wondering, how to change the title of Generated PDF?
Like, it shows the title , which i've set in Jasper Studio. But i want to alter it when it generates in laravel, like with time stamp + Name.

Thanks

**Comment by geekcom** [comment]
Hi @Karacraft thanks for use PHPJasper, please check the forums about [JasperSoft](https://community.jaspersoft.com/wiki/how-use-timestamp-parameter).
