### ISSUE TITLE
Problemas de acentuação

### ISSUE THREAD

**Issue by schenato** [PHPJasper/phpjasper#163]
Bom dia, estou com os seguintes problemas de acentuação. Quando enviado via parâmetros um titulo "Relatório" no textfield do jasper quando gera o mesmo está saindo da seguinte forma "Relatrio" está sumindo as letras que possuem acentuação. O locale que estou usando é pt_BR,
quando coloco no default do textfield o valor "Relatório" e não passo via parâmetro sai corretamente a impressão do PDF.
O que poderia ser, já tentei corrigir diversas vezes, mas sem êxito.

**Comment by neylsongularte** [comment]
+1

**Comment by neylsongularte** [comment]
coloca isso antes de gerar o relatório

$locale = 'pt_BR.utf-8';
        setlocale(LC_ALL, $locale);
        putenv('LC_ALL='.$locale);

**Comment by schenato** [comment]
Deu certo, obrigado.

**Comment by geekcom** [comment]
@schenato Coisa linda ver a comunidade se movimentando sozinha.

**Comment by schenato** [comment]
@geekcom é sim hehehehe
