### ISSUE TITLE
Library initialization failed

### ISSUE THREAD

**Issue by emanuellimabr** [PHPJasper/phpjasper#164]
**Describe the bug**
I am facing the following issue when I try to use this library in an Linux environment:

 _**"library initialization failed - unable to allocate file descriptor table - out of memory"**_

**To Reproduce**
      

        
        $input = public_path('storage/reports') . '/examples/hello_world.jrxml';
        $this->jasper->compile($input)->execute();

        $input = public_path('storage/reports') . '/examples/hello_world.jasper';
        $output = public_path('storage/reports') . '/examples';

        $options = [
            'format' => ['pdf', 'rtf'],
        ];

        $this->jasper->process(
            $input,
            $output,
            $options
        )->execute();

**Expected behavior**
It should generate two files in the examples directory

**Desktop:**
 - OS: [Linux Manjaro]
 - PHP [7.3.8]
 - Apache [2.4.39]
 - JDK [1.8]

**Comment by geekcom** [comment]
Hi @emanuellimabr please check [here](https://stackoverflow.com/questions/49435109/error-upon-jar-execution-unable-to-allocate-file-descriptor-table)

**Comment by emanuellimabr** [comment]
It has solved my problem. I basically add the following command to the jasperstarter file inside bin directory.

`ulimit -n 10000`
`java -jar "$HOME_FOLDER/lib/jasperstarter.jar" "$@"`
