### ISSUE TITLE
Not showing Chinese character

### ISSUE THREAD

**Issue by game09488** [PHPJasper/phpjasper#165]
Hi, 

Im using Laravel 5.7 to generate a report, the output was good I can see the pdf successfully generated but it is not showing Chinese characters. Can someone please help?

**Screenshots**
![Screenshot 2019-09-06 at 12 42 02 PM](https://user-images.githubusercontent.com/38254516/64401496-c67f7800-d0a3-11e9-9639-18c65f8cab35.png)

Expected:
![Screenshot 2019-09-06 at 12 42 21 PM](https://user-images.githubusercontent.com/38254516/64401499-cc755900-d0a3-11e9-9be2-e5f0c99fded2.png)

**Desktop**
 - OS: macOS 10.14.6
 - Browser: Chrome

**Comment by geekcom** [comment]
Hi @game09488 is possible to configure locale for reports, below an example for Chinese Simplified locale.

For a complete list of locales see [Supported Locales](https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html)




```php
$options = [
    'format' => ['pdf'],
    'locale' => 'zh_CN',
    'params' => [],
    'db_connection' => [
        'driver' => 'mysql',        
        'username' => 'DB_USERNAME',
        'password' => 'DB_PASSWORD',
        'host' => 'DB_HOST',
        'database' => 'DB_DATABASE',
        'port' => '5432'
    ]
];

**Comment by game09488** [comment]
> Hi @game09488 is possible to configure locale for reports, below an example for Chinese Simplified locale.
> 
> For a complete list of locales see [Supported Locales](https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html)
> 
> ```
> $options = [
>     'format' => ['pdf'],
>     'locale' => 'zh_CN',
>     'params' => [],
>     'db_connection' => [
>         'driver' => 'mysql',        
>         'username' => 'DB_USERNAME',
>         'password' => 'DB_PASSWORD',
>         'host' => 'DB_HOST',
>         'database' => 'DB_DATABASE',
>         'port' => '5432'
>     ]
> ];
> ```

I did, but still not showing...

<img width="185" alt="Screenshot 2019-09-06 at 9 40 18 PM" src="https://user-images.githubusercontent.com/38254516/64432488-3b2bd400-d0ef-11e9-9eb8-a45629a8295f.png">

<img width="486" alt="Screenshot 2019-09-06 at 9 41 46 PM" src="https://user-images.githubusercontent.com/38254516/64432491-3bc46a80-d0ef-11e9-84ec-5cdc50136489.png">

**Comment by game09488** [comment]
@geekcom one more thing is that I hope you can improve the error message, it is hard for us to find the bugs...

<img width="1642" alt="Screenshot 2019-09-08 at 6 39 55 PM" src="https://user-images.githubusercontent.com/38254516/64487067-435b4f00-d268-11e9-95e5-1f475cb469cf.png">

**Comment by geekcom** [comment]
> @geekcom one more thing is that I hope you can improve the error message, it is hard for us to find the bugs...
> 
> <img alt="Screenshot 2019-09-08 at 6 39 55 PM" width="1642" src="https://user-images.githubusercontent.com/38254516/64487067-435b4f00-d268-11e9-95e5-1f475cb469cf.png">

PHPJasper errors are at JDK level, so they are hard to find, but you can use the `output()` method instead of `execute()` to see the command generated, and execute the command generated direct in the path /bin/jasperstarter/bin, to find possible errors.

_Note_: from 3.0.1 version the output() method it's self sufficient(don't need a PHP print method to work)
