### ISSUE TITLE
Support to html component

### ISSUE THREAD

**Issue by emanuellimabr** [PHPJasper/phpjasper#166]
**Describe the bug**
I am getting this error while trying to compile a jrxml file that embeeds an html component : 

_**net.sf.jasperreports.engine.JRRuntimeException: Unknown entity http://jasperreports.sourceforge.net/xsd/htmlcomponent.xsd, not loading.**_

**To Reproduce**
`
<hc:html xmlns:hc="http://jasperreports.sourceforge.net/htmlcomponent" xsi:schemaLocation="http://jasperreports.sourceforge.net/htmlcomponent http://jasperreports.sourceforge.net/xsd/htmlcomponent.xsd" scaleType="RetainShape" horizontalAlign="Left" verticalAlign="Middle">
                    <hc:htmlContentExpression></hc:htmlContentExpression>
                </hc:html>
`

**Screenshots**
Here is how it is being showed on jasperstudio previewing
![selo](https://user-images.githubusercontent.com/2726721/64618371-83304c80-d3b6-11e9-910e-c9ffdfcc7d8a.png)

**Additional context**
I have tried to follow this link:
https://stackoverflow.com/questions/1091760/export-html-content-to-pdf-using-jasperreports
but no success.
Does anyone know how to add this component to the lib?

**Comment by emanuelcd** [comment]
amigo, bom dia, vc conseguiu resolver o problema da impressao com HtmlComponent ?? estou com a mesma dificuldade.

msg erro:  Unknown entity

**Comment by emanuellimabr** [comment]
> amigo, bom dia, vc conseguiu resolver o problema da impressao com HtmlComponent ?? estou com a mesma dificuldade.
> 
> msg erro: Unknown entity

Amigo, a solução foi usar a versão 6.6 do jasper studio para gerar os relatórios. Até essa versão, funciona perfeitamente, depois dela houve alguma atualização que acabou gerando esse bug. Espero que funcione com você também.
