### ISSUE TITLE
Adding capability to use other fonts

### ISSUE THREAD

**Issue by yuzrie** [PHPJasper/phpjasper#167]
**Is your feature request related to a problem? Please describe.**
I cannot find a way to use "Times New Roman" font in PHPJasper. In JasperSoft Studio, its outputting correctly using Times New Roman, when used with PHPJasper, the font changed to some sans font (I'm guessing its Arial). This is important because of some clients are old and cannot differentiate at a glance numbers like 3, 8 and 9.

**Describe the solution you'd like**
It'd be nice, if we can put the required font into any folder that PHPJasper will look at.. maybe inside the config file, we can have something like `config/phpjasper.php`
```php
'fonts' => _DIR_ . 'public/fonts'
```

**Describe alternatives you've considered**
If can put the fonts from the options that is also fine:
```php
$options = [
            'format' => ['pdf'],
            'fonts' => _DIR_ . 'public/fonts', // this part here
            'params' => [],
            'locale' => 'en',
            'db_connection' => [
                'driver' => 'json',
                'data_file' => $data_file,
                'json_query' => 'DATA'
            ]
        ];
```

**Additional context**
By the way, I'm developing on Laravel 5.8 on Windows using Laragon, so the suggestion I gave may not seem so generic.

**Comment by yuzrie** [comment]
Its been a while already and I'm still waiting for an answer. Is there any other methods or workaround currently available? or do I need to have the font installed within the OS? 

any clues are appreciated

**Comment by geekcom** [comment]
Hi @mohamadyuzrie you need the font installed on your OS.

**Comment by adummy832** [comment]
@geekcom, This shouldn't be closed. As stated here [JasperStarter - Running JasperReports from command line](http://jasperstarter.cenote.de/unicode-pdf-export.html#Using_a_font_with_JasperStarter).  
We can include external .jar files and should be automatically included.
Been facing this kind of issue right now. Default jasper fonts didnt include support for Ñ/ñ. 
Unicode crap, etc etc.

Useful links:
[Custom Font with the Font Extension](https://community.jaspersoft.com/wiki/custom-font-font-extension)

**Comment by yuzrie** [comment]
I can confirm, the putting the font.jar into jdbc works. but to manually put stuff into vendor/ doesn't sit right with me. I mean, now I'm using that way but what if one day I do composer update or something wouldn't the fonts be gone then. but I think this is problem with jasperstarter right.. so nothing we can do also.. if there's a way to make jasperstarter look at some other directory instead of its own jdbc/ that should settle the issue

**Comment by yuzrie** [comment]
actually hold that thought.. I saw the font changing but I'm getting a ???? for Chinese characters I tried meiryo and arial unicode ms... both also shows this while they're supposed to support chinese characters as far as I know.. where could the problem be? it works in jasper studio though

**Comment by yuzrie** [comment]
It seems like we cannot pass Chinese characters from params, it will show ????, but when I save the object into a json string into a json file, for example 他不爱我 will convert to \u4ed6\u4e0d\u7231\u6211 .. this one can be shown correctly 他不爱我 in the generated pdf
