### ISSUE TITLE
Write unit new unit tests

### ISSUE THREAD

**Issue by geekcom** [PHPJasper/phpjasper#171]
https://phpunit.de/

**Comment by davidribeiro** [comment]
Hi @geekcom you need any help with this?

**Comment by geekcom** [comment]
Hi @davidribeiro we need more tests.

**Comment by davidribeiro** [comment]
I can help if you want to. Anything particular to test or do you just want more code coverage?

**Comment by geekcom** [comment]
> I can help if you want to. Anything particular to test or do you just want more code coverage?

Just more coverage at the moment.

**Comment by davidribeiro** [comment]
I'm currently having 4 errors while running the tests, it's this supposed to happen?

- testCompile
- testProcess
- testListParameters
- testCompileHelloWorld

**Comment by geekcom** [comment]
a moment I'll test

**Comment by davidribeiro** [comment]
I figured it out, you're using assertRegExp but the output method doesn't return anything, the current method to use in the test is expectOutputRegex

**Comment by davidribeiro** [comment]
Done in #172 , any feedback is appreciated!

**Comment by geekcom** [comment]
https://github.com/PHPJasper/phpjasper/pull/172
