### ISSUE TITLE
Error filling reportResource not found

### ISSUE THREAD

**Issue by ormenese** [PHPJasper/phpjasper#175]
Tenho um relatório com subreport funcionando no Jasper. Quando tento executar pelo phpjasper recebo o erro : 

> "Error filling reportResource not found".

- Já atualizei, pelo composer, para a versão 3.0.1 
- Já passei o caminho do subreport por caminho absoluto através de parâmetro.
- O subreport é referenciado pela extensão compilada .Jasper no relatório principal. 
- Todos os arquivos .Jasper estão na mesma pasta (relatório principal e sub).

Alguma dica do que pode ser ???

Segue código da chamada do subreport no relatório principal:

`<detail>
	<band height="34">
		<subreport>
			<reportElement x="0" y="4" width="797" height="15" isRemoveLineWhenBlank="true" uuid="8948865a-e0fd-4fa9-a681-c68fd55a2a3f">
				<property name="com.jaspersoft.studio.unit.width" value="px"/>
				<property name="com.jaspersoft.studio.unit.height" value="px"/>
				<property name="com.jaspersoft.studio.unit.x" value="px"/>
				<property name="com.jaspersoft.studio.unit.y" value="px"/>
				<printWhenExpression><![CDATA[$P{tipo_relatorio}.equals( "detalhado" )]]></printWhenExpression>
			</reportElement>
			<subreportParameter name="dtini_transf_det">
				<subreportParameterExpression><![CDATA[$P{dtini}]]></subreportParameterExpression>
			</subreportParameter>
			<subreportParameter name="dtfinal_transf_det">
				<subreportParameterExpression><![CDATA[$P{dtfinal}]]></subreportParameterExpression>
			</subreportParameter>
			<subreportParameter name="tipo_fatura_transf_det">
				<subreportParameterExpression><![CDATA[$P{tipo_fatura}]]></subreportParameterExpression>
			</subreportParameter>
			<subreportParameter name="servico_transf_det">
				<subreportParameterExpression><![CDATA[$F{servreq}]]></subreportParameterExpression>
			</subreportParameter>
			<connectionExpression><![CDATA[$P{REPORT_CONNECTION}]]></connectionExpression>
			<subreportExpression><![CDATA[$P{caminho_subreport} +"/fatura_servico_transf_detalhado.jasper"]]></subreportExpression>
		</subreport>
	</band>
</detail>`

**Comment by geekcom** [comment]
Oi @ormenese executa o método `output();`, e cola aqui o retorno.

**Comment by ormenese** [comment]
Dei uma olhada no jasperstarter e vi uma dica deles que fala para utilizar o Data Source Expression = $P{REPORT_DATA_SOURCE}, ao invés do Connection Expression = $P{REPORT_CONNECTION}.
Eu fiz isso, mas o erro continua o mesmo.

Segue saída do método output():

jasperstarter --locale pt_BR process "C:\Bitnami\wapp\apache2\htdocs\jasper/vendor/geekcom/phpjasper/rastro/fatura_servico_t.jasper" -o "C:\Bitnami\wapp\apache2\htdocs\jasper/vendor/geekcom/phpjasper/rastro/relat_pronto/" -f pdf -P caminho_imagem="C:/Bitnami/wapp/apache2/htdocs/images/logo_hemo_relat.jpg" dtini="01/01/2018" dtfinal="31/01/2018" tipo_relatorio="detalhado" tipo_fatura="Não SUS" caminho_subreport="C:/Bitnami/wapp/apache2/htdocs/vendor/geekcom/phpjasper/rastro" -t postgres -u xxx -p xxx -H xxx -n xxx --db-port 6432 -r C:/Bitnami/wapp/apache2/htdocs/vendor/geekcom/phpjasper/rastro/

**Comment by geekcom** [comment]
Roda a saida do método output dentro da pasta do executável `bin/jasperstarter/bin/`, via terminal, depois posta aqui o resultado.

**Comment by ormenese** [comment]
Error filling reportResource not found at: fatura_servico_transf_detalhado.jasper.

**Comment by ormenese** [comment]
geekcom, encontrei o erro !!!
O parâmetro caminho_subreport estava errado e consequentemente o "-r " também ficou errado.
Agora está rodando 100%.
Muito obrigado pela atenção !!!

**Comment by geekcom** [comment]
Maravilha, vou fechar a issue então.

**Comment by PedroLucca** [comment]
> geekcom, encontrei o erro!!! O parâmetro caminho_subreport estava errado e consequentemente o "-r" também ficou errado. Agora está rodando 100%. Muito obrigado pela atenção!!!

poderia esclarecer como fez a correção? estou enfrentando mesmo problema e não estou sabendo como especificar direito o caminho do subReport
