### ISSUE TITLE
Issue to generate de report when using database from a server

### ISSUE THREAD

**Issue by dev-gustaavo** [PHPJasper/phpjasper#177]
Possuo uma base de desenvolvimento, que está publicada em um servidor e quando uso ela para gerar o relatório, recebo o seguinte erro: usage: jasperstarter process [-h] -f <fmt> [<fmt> ...] [-o <output>] [-w] [-a [<filter>]].

![image](https://user-images.githubusercontent.com/19441895/66530321-a8ab9580-eadd-11e9-927b-6ddefa49b690.png)

Porém, quando uso meu banco local, usando localhost, ele funciona normalmente. Sabe dizer o motivo disso acontecer e como solucionar?

**Comment by geekcom** [comment]
Olá @DeveloperGustavo use o método output() para entender qual o erro, com copie o comando gerado pelo método e execute diretamente no bash do seu servidor.
