### ISSUE TITLE
PHPJasper\Exception\ErrorCommandExecutable Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.

### ISSUE THREAD

**Issue by ryangp** [PHPJasper/phpjasper#178]
```
$bio_num = 11461;
$jasper = new PHPJasper;

$jasperinput = public_path().'/jasperinputs/EmployeeData.jrxml';
		$jasperoutput = public_path().'/jasperoutputs/'.$bio_num;
		$pdfreports = public_path().'/pdfreports';
		$outputoption = [
			'format' => ['pdf'],
			'locale' => 'en',
			'params' => ['bio_num' => $bio_num],
			'db_connection' => [
				'driver' => 'mysql',
				'username' => 'root',
				'password' => '',
				'host' => 'localhost',
				'database' => 'hris_db',
				'port' => '3306'
			]
		];
		$jasper->process(
			$jasperinput,
			$jasperoutput,
			$outputoption
		)->execute();
```

I used this code to run jrxml file containing parameter. but a error shows after running it to the browser.

`PHPJasper\Exception\ErrorCommandExecutable
Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.`

But when executing jrxml file without parameter(s) It executes without error and can produce pdf file.

How can I resolve this error. I need to put parameters to get specific data from database.
I am looking for your response. Thank you.

**Comment by ryangp** [comment]
I try to run the output command in jasperstarer console. 

`jasperstarter process "D:\Laravel Project\Website\www.kap-hris.gov.ph\public/jasperinputs/EmployeeData.jrxml" -o "D:\Laravel Project\Website\www.kap-hris.gov.ph\public/jasperoutputs/11461" -f pdf -P bio_num="11461" -t mysql -u root -p -n hris_db -H localhost --db-port 3306`

I get error 

> You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

> and -p need a parameter something like that.

I keep searching seeking for answer and finally. I made it work without error.
What I did was
**1. Change the jar files with filename something like "mysql.xxxx" inside  /vender/geekcom/phpjasper/bin/jasperstarter/jdbc/** with this mysql connector version
`mysql-connector-java-5.1.48.jar`

**2. Make the option parameter like this.**
                        ```
$outputoption = [
				'format' => ['pdf'],
				'params' => [
					'bio_num' => $bio_num
				],
				'db_connection' => [
					'driver' => 'mysql',
					'username' => 'root',
					'password' => '""',
					'database' => 'hris_db',
					'host' => 'localhost',
					'port' => '3306'
				]
			];
```
Take a look at password value. That is very important. Its because when you remove the double qoute inside single quote it will throw an error saying, -p needs a parameter blah blah blah....

Thanks geekcom for your package.
For the other developer hope this will you.

**Comment by geekcom** [comment]
Thanks for tip @ryangp

**Comment by DanielDDsj** [comment]
I'm getting the error:
**No input file**
 when i'm trying to do like the exemple:

use PHPJasper\PHPJasper;

$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jrxml';

    $jasper = new PHPJasper;
    $jasper->compile($input)->execute();


$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jasper';  
$output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    
$options = [ 
    'format' => ['pdf', 'rtf'] 
];

$jasper->process(
    $input,
    $output,
    $options
)->execute();

What can i do?
I'm trying to solve this, 3 months ago. please, help me!!!

**Comment by addin27023** [comment]
Double Click on "jasperstarter.exe" then it will open chrome and go to java download page.
Download and install java, then try run jasper on your application (PHP).

I done that. After install Java everything works fine.

https://java.com/en/download/
