### ISSUE TITLE
Gerar Relatório de uma Variável JSON / Generating Report from a JSON Variable

### ISSUE THREAD

**Issue by isaacbatista** [PHPJasper/phpjasper#18]
Olá, 
No Laravel, consigo gerar um relatório com um arquivo JSON. Mas se eu gerasse este JSON de um Array vindo do DB. Como poderia ser feito isso? 
Tipo: Somente através de um arquivo JSON que eu conseguiria gerar um relatório???
Me ajudem nisso por favor!!!

Hello, 
In Laravel, I can generate a report with a JSON file. But if I generated this JSON from an Array coming from DB. How could that be done?
Type: Only through a JSON file that I could generate a report ???
Help me on this please !!!

**Comment by geekcom** [comment]
Olá @isaacbatista , vamos a resposta.

- Você precisa de uma fonte de dados do tipo json;
- No Jasper Studio ou outra ferramenta de sua escolha você deve criar seu modelo de relatório .jrxml, o próprio Jasper Studio compila em .jasper, ou você pode compilar usando a lib veja no readme.md como;
- Abaixo vou te passar um exemplo de como gerar um relatório a partir de um json sem usar qualquer Framework.

Para usar o exemplo você precisa ter o composer instalado e depois executar o comando `composer install`

[Exemplo completo](https://github.com/geekcom/phpjasper/files/640450/report_from_a_json.zip)

```php
$input = __DIR__ . '/input/report_json.jasper';
$output = __DIR__ . '/output';

$data_file = __DIR__ . '/data-source-json/contacts.json';
$json_query= "contacts.person";

$driver = 'json';
$format = 'pdf';
$locale = 'en';


$jasper = new JasperPHP;

$jasper->process(
	$input,
	$output,
	$format,
	[],
	[
	    'data_file' => $data_file,
	    'driver' => $driver,
	    'json_query' => $json_query
	],
	$locale
)->execute();

**Comment by geekcom** [comment]
Hello @isaacbatista, let's answer.

- You need a json data source;
- In Jasper Studio or another tool of your choice you should create your .jrxml report template, Jasper Studio itself compiles into .jasper, or you can compile using the lib view in readme.md as;
- Below I will give you an example of how to generate a report from a json without using any Framework.

Here is the complete download example:
[Full Example](https://github.com/geekcom/phpjasper/files/640450/report_from_a_json.zip)

**Comment by isaacbatista** [comment]
@geekcom é inevitável o uso da fonte de dados JSON ser realizada através de arquivo .JSON?
Não poderíamos puxar um resultado de um Banco SQL, coloca-lo em um Array e transformar este Array em um JSON e usá-lo no iReport????

Assim:
`
$municipios = $this->MunicipiosRepository->all()->toArray();
$json['municipios'] = $municipios;

$jsn = json_encode($json);
`
Algum exemplo neste caso?

===================================================================

@geekcom is it inevitable to use the JSON data source be held through .JSON file?
We could not pull a result from a SQL Bank, put it in an Array and turn this Array into a JSON and use it in iReport ????

Like this:

`
$municipios = $this->MunicipiosRepository->all()->toArray();
$json['municipios'] = $municipios;

$jsn = json_encode($json);
`
Any examples in this case?

**Comment by geekcom** [comment]
@isaacbatista, deve existir uma forma, ainda não precisei usa-la, seria uma grande ajuda para a comunidade que usa a biblioteca.

------

There must be a way, I have not yet had to use it, it would be a great help to the community that uses the library.
