### ISSUE TITLE
Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /homepages/26/d797149918/htdocs/sifypp/vendor/geekcom/phpjasper/src/PHPJasper.php:219 Stack trace: #0 /homepages/26/d797149918/htdocs/sifypp/marcoLogico/reportes/rep_definicion.php(32): PHPJasper\PHPJasper->execute() #1 {main} thrown in /homepages/26/d797149918/htdocs/sifypp/vendor/geekcom/phpjasper/src/PHPJasper.php on line 219

### ISSUE THREAD

**Issue by said-omar** [PHPJasper/phpjasper#180]
How are you, I am using your resource and I found this error and I could not solve it. I will attach my code

`require __DIR__ . '/../../vendor/autoload.php';
use PHPJasper\PHPJasper;    
include_once('../../conexion/db.conexion.php'); 
$data = new Connection();

$id= base64_decode($_GET["id"]);
$input =  __DIR__ . '/jasper/objetivo.jasper';   
$output =  __DIR__ . '/pdf';
$options = [
    'format' => ['pdf'],
    'locale' => 'en',
    'params' => [
        'mml' => $id
    ],
    'db_connection' => [
        'driver' => 'mysql',
        'username' => $data ->username,
        'password' => $data ->password,
        'host' => $data->host,
        'database' => $data->database,
        'port' => $data->port
    ]
];

$jasper = new PHPJasper;

$jasper->process(
        $input,
        $output,
        $options
)->execute();
`

**Comment by geekcom** [comment]
Hi @said-omar please try to run the outputed command in jasperstarer console.

**Comment by said-omar** [comment]
I already did it and got the following "C:\wamp\www\Presupuestov3\marcoLogico\reportes/jasper/analisis.jasper" -o "C:\wamp\www\Presupuestov3\marcoLogico\reportes/pdf" -f pdf -P mml="1" -t mysql -u hugo -p hugo -H 192.168.1.155 -n presupuestos --db-port 3306

**Comment by malsmary** [comment]
Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\wamp64\www\sham\vendor\geekcom\phpjasper\src\PHPJasper.php on line 219

**Comment by malsmary** [comment]
what

**Comment by malsmary** [comment]
??

**Comment by rafaabraham** [comment]
hi bro, has this bug been solved? I have the same problem, please help me if you have found it
