### ISSUE TITLE
phpjasper da erro com o postgres e parametro

### ISSUE THREAD

**Issue by Danillosdd** [PHPJasper/phpjasper#181]
Ao usar a bibliotca phpjasper no hello world foi com sucesso, mais ao tentar com conexão no banco e parametro dá este erro abaixo, estou utilizando o xampp e o postgres:

Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\src\PHPJasper.php:221 Stack trace: #0 C:\xampp\htdocs\relatorio\venda.php(29): PHPJasper\PHPJasper->execute() #1 {main} thrown in C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\src\PHPJasper.php on line 221

Meu Arquivo .php que chama a bilioteca está assim:

```
<?php

require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;    

$input = '/vendor/geekcom/phpjasper/examples/venda.jasper';   
$output = '/vendor/geekcom/phpjasper/examples';
$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => [5],
    'db_connection' => [
        'driver' => 'postgres',
        'username' => 'postgres',
        'password' => 'honeypot',
        'host' => 'localhost',
        'database' => 'nathusa',
        'port' => '5432'
    ]
];

$jasper = new PHPJasper;

$jasper->process(
        $input,
        $output,
        $options
)->output();
	
	
	
	
?>

```

**Comment by jadsonbr** [comment]
Please use block code for a better view of your code so we can help you.

Option insert code in icon `< >`

**Comment by Danillosdd** [comment]
alterei

**Comment by jadsonbr** [comment]
Existe o relatório **venda.jasper** dentro no diretório informado ?

`/vendor/geekcom/phpjasper/examples/venda.jasper`

**Comment by Danillosdd** [comment]
Sim, 

ja tentei executar o .jrxml e com o .jasper tbm

**Comment by Danillosdd** [comment]
Fiz a edição no texto do codigo pois com execute dava este erro, e verifiquei que a orientação era usar outuput, mais usando output ocorre o erro:

`jasperstarter --locale pt_BR process "/vendor/geekcom/phpjasper/examples/venda.jasper" -o "/vendor/geekcom/phpjasper/examples" -f pdf -P 0="5" -t postgres -u postgres -p honeypot -H localhost -n nathusa --db-port 5432`

**Comment by jadsonbr** [comment]
Altere **NOME_PARAMETRO** para o nome do parâmetro correspondente no seu relatório.

E tente o seguinte:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;    

$input = '/vendor/geekcom/phpjasper/examples/venda.jasper';   
$output = '/vendor/geekcom/phpjasper/examples';
$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => [
         'NOME_PARAMETRO' => 5,
    ],
    'db_connection' => [
        'driver' => 'postgres',
        'username' => 'postgres',
        'password' => 'honeypot',
        'host' => 'localhost',
        'database' => 'nathusa',
        'port' => '5432'
    ]
];

$jasper = new PHPJasper;

$jasper->process(
        $input,
        $output,
        $options
)->execute();

?>
```

**Comment by Danillosdd** [comment]
Ocorre o erro:

`Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\src\PHPJasper.php:221 Stack trace: #0 C:\xampp\htdocs\relatorio\venda.php(31): PHPJasper\PHPJasper->execute() #1 {main} thrown in C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\src\PHPJasper.php on line 221`

**Comment by Danillosdd** [comment]
Obs.:

Ao visualizar no Irepot o .jrxml, pede a senha do database, talvez o erro seja porque o meu database tem senha, num sei...

**Comment by jadsonbr** [comment]
Abra o seu prompt de comando e navegue até a pasta onde se encontra o jasperstarter.exe.
`C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\bin\jasperstarter\bin`

Execute o comando abaixo e nos mande o que retornou.

```
jasperstarter --locale pt_BR process "/vendor/geekcom/phpjasper/examples/venda.jasper" -o "/vendor/geekcom/phpjasper/examples" -f pdf -t postgres -u postgres -p honeypot -H localhost -n nathusa --db-port 5432
```

**Comment by Danillosdd** [comment]
engraçado não está encontrado o arquivo.. ta buscando no diretorio errrado

`Error: file not found: C:\vendor\geekcom\phpjasper\examples\venda.jasper`

**Comment by Danillosdd** [comment]
vou ter que colocar o endereço completo, está buscando neste diretorio, e nele não tem mesmo, o diretório completo seria:

C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples\venda.jasper

**Comment by jadsonbr** [comment]
Correto.
Você estava tentando executar com a estrutura de diretório do linux mais você está no windows.
Terá que ajustar isso.

**Comment by Danillosdd** [comment]
agora acusou

```
jasperstarter' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
```

**Comment by Danillosdd** [comment]
meu arquivo php ficou assim:
```
<?php

require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;    

$input = 'C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples\venda.jasper';   
$output = 'C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples';
$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => [
         'NOME_PARAMETRO' => 5,
    ],
    'db_connection' => [
        'driver' => 'postgres',
        'username' => 'postgres',
        'password' => 'honeypot',
        'host' => 'localhost',
        'database' => 'nathusa',
        'port' => '5432'
    ]
];

$jasper = new PHPJasper;

$jasper->process(
        $input,
        $output,
        $options
)->output();

?>
```

**Comment by Danillosdd** [comment]
e o erro no browser ficou:

```
jasperstarter --locale pt_BR process "C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples\venda.jasper" -o "C:\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples" -f pdf -P NOME_PARAMETRO="5" -t postgres -u postgres -p honeypot -H localhost -n nathusa --db-port 5432
```

**Comment by Danillosdd** [comment]
tinha executado o codigo no lugar errado

**Comment by Danillosdd** [comment]
deu o erro no nome do parametro e corrigi

**Comment by Danillosdd** [comment]
agora está dando:

```
Error filling reportByte data not found at: logo-nathusa2.jpg.
```

**Comment by Danillosdd** [comment]
a imagem está no ireport, tem que passar parametro de imagem no arquivo php?

**Comment by jadsonbr** [comment]
O diretório da imagem você deve definir no **resources** ou passar o caminho absoluto.

**Comment by Danillosdd** [comment]
estava usando o windows passei pro linux ao ir na pasta do jasperstar e executar o comando:

```
./jasperstarter --locale pt_BR process "D:\Arquivos de Programas\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples\venda.jasper" -o "D:\Arquivos de Programas\xampp\htdocs\relatorio\vendor\geekcom\phpjasper\examples" -f pdf -P parametroprincipal="5" -t postgres -u postgres -p @Mega2019 -H localhost -n nathusa --db-port 5432
```

sudo: ./jasperstarter: comando não encontrado

como é a execução no linux?

**Comment by Danillosdd** [comment]
Consegui resolver a situação acima, reinstalando o composer, e mandando instalar o phpjasper de novo.

**Comment by Danillosdd** [comment]
Só que agora ao executar o comando 

```
./jasperstarter --locale pt_BR process "D:\Arquivos de Programas\xampp\htdocs\relatorio2\vendor\geekcom\phpjasper\examples\venda.jasper" -o "D:\Arquivos de Programas\xampp\htdocs\relatorio2\vendor\geekcom\phpjasper\examples" -f pdf -P parametroprincipal="5" -t postgres -u postgres -p honeypot -H localhost -n nathusa --db-port 5432
```

Retorna:

```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:75)
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:65)
	at de.cenote.tools.classpath.ApplicationClasspath.addJars(ApplicationClasspath.java:134)
	at de.cenote.tools.classpath.ApplicationClasspath.addJarsRelative(ApplicationClasspath.java:151)
	at de.cenote.jasperstarter.App.processReport(App.java:178)
	at de.cenote.jasperstarter.App.main(App.java:109)

```

**Comment by Danillosdd** [comment]
Reintalei o Java como sdkman, e deu certo agora, gerou o pdf

**Comment by Danillosdd** [comment]
a dúvida agora.

creio que seja a última...rs..

porque pra conseguir gerar o pdf eu estou tendo que executar o comando na pasta jasperstarter pra gerar o relatório..

no arquivo.php com o comando execute da erro de output..
no arquivo.php  com output ele gera este codigo:  
```
./jasperstarter --locale pt_BR process "D:\Arquivos de Programas\xampp\htdocs\relatorio2\vendor\geekcom\phpjasper\examples\venda.jasper" -o "D:\Arquivos de Programas\xampp\htdocs\relatorio2\vendor\geekcom\phpjasper\examples" -f pdf -P parametroprincipal="5" -t postgres -u postgres -p honeypot -H localhost -n nathusa --db-port 5432
```
que tenho que executá-lo na pasta do 

```
/opt/NetMake/v9/wwwroot/relatorio2/vendor/geekcom/phpjasper/bin/jasperstarter/bin
```

pra gerar o pdf pelo terminal.

Como faço pra gerar o pdf direto pelo arquivo.php

**Comment by Danillosdd** [comment]
E Desde já te Agradeço @jadsonbr

**Comment by Danillosdd** [comment]
Com as orientações do @jadsonbr deu certo, era questão de permissão das pastas...

Vlw... Demais.... Pela Força.....

***********RESOLVIDO**********

Eu usava antes a bilioteca phpjaspexml, https://github.com/SIMITGROUP/phpjasperxml mais ela tinha muitos problemas de implementação e subreport, com essa via ficar bem melhor.
