### ISSUE TITLE
Doubt for used phpjasper

### ISSUE THREAD

**Issue by eduardo12fox** [PHPJasper/phpjasper#184]
I get example on git but not run for me. Help-please

show error: Fatal error: Uncaught Error: Class 'JasperPHP\JasperPHP' not found in C:\xampp\htdocs\jasper\teste.php:14 Stack trace: #0 {main} thrown in 
Below my script:

<?php

require __DIR__ . '/vendor/autoload.php';

use JasperPHP\JasperPHP;

// Na linha abaixo utilize o .JRXML ao invés do .JASPER
$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jrxml';
$output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    
$options = [ 
    'format' => ['pdf', 'rtf'] 
];

$jasper = new JasperPHP;

echo 
    $jasper->process(
    $input,
    $output,
    $options
)->output();
?>

**Comment by geekcom** [comment]
Hi @eduardo12fox the correct name of class is `PHPJasper`, please see the docs.

**Comment by eduardo12fox** [comment]
Olá, ora mas é a mesma que eu coloquei no exemplo assim, não vi nada de diferente onde está errado no meu exemplo?

**Comment by eduardo12fox** [comment]
Olá, insistindo mais um pouco na dúvida, após fazer a correção tenho esse erra na minha hospedagem:
Warning: exec() has been disabled for security reasons in 

Tem como trocar o exec() por outro? Acredito que seja limitação da Kinghost

**Comment by eduardo12fox** [comment]
Depois de corrigir o problema e ver com meu provedor a questão do exec agora tenho um novo erro:

Fatal error: Uncaught PHPJasper\Exception\InvalidInputFile: No input file in ...

Segue meu script:

require 'vendor/autoload.php';

use PHPJasper\PHPJasper;

$input  = 'vendor/geekcom/phpjasper/examples/TemplateData03.jrxml';   

$output =  'vendor/geekcom/phpjasper/examples';  

$jasper = new PHPJasper;
$jasper->compile($input)->execute();

**Comment by DanielDDsj** [comment]
@eduardo12fox, também estou com o problema do exec, ao gerar relatórios com jasper no laravel. Como foi que resolveste este problema? Por favor, ajuda-me.
