### ISSUE TITLE
Is there anyway to integrate with codeigniter 4 php 7+ ? Searching & looking for answer yet not found. Hope the features can be discussed and provided either by PHPJasper or any contributors

### ISSUE THREAD

**Issue by gilbertlow** [PHPJasper/phpjasper#187]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geekcom** [comment]
Hi @gilbertlow PHPJasper is independently of Frameworks, just follow the docs.
