### ISSUE TITLE
How to print jasper report without preview in Laravel 5

### ISSUE THREAD

**Issue by hirantha19** [PHPJasper/phpjasper#19]
I generated pdf file and save it in the report directory. So I need to direct this pdf file to the client's printer without open it on the browser. I think this is possible in java. So is it possible in Laravel..?

**Comment by geekcom** [comment]
Hi @hirantha19, I do not know any way to do this using PHP or laravel, but it is possible using javascript see in this [LINK](http://stackoverflow.com/questions/7074070/how-to-send-a-pdf-file-directly-to-the-printer-using-javascript)
