### ISSUE TITLE
Servidor embutido do php trava ao processar e executar o relatório

### ISSUE THREAD

**Issue by alexandrejonathas** [PHPJasper/phpjasper#196]
Quando executo esse output no terminal o relatório é gerado sem problemas.
 jasperstarter process "C:\dev\workspace\php\fila\public\reports\relatorio\atendimento_sintetico.jasper" -o "C:\dev\workspace\php\fila\public\reports\1576158063_atendimentos_sintetico" -f pdf -P image_url="http://localhost:8000/assets/images/logo.png" data_inicio="2019-01-01" data_fim="2019-01-30" status="CONCLUIDA" -t postgres -u postgres -p postgres -H 127.0.0.1 -n consysti_fila --db-port 5432 --jdbc-dir C:\dev\workspace\php\fila\storage\jdbc.

Porém ao mudar para execute o relatório não é gerado e o servidor trava.

Estou usando windows para desenvolvimento, alguma sugestão do que possa estar causando o travamento?

**Comment by geekcom** [comment]
Oi @alexandrejonathas use o método `printOutput()` para gerar o comando, copie o comando gerado e execute na pasta do arquivo binário `/bin/jasperstarter/bin`, assim se tiver algum erro será mostrado nesse momento.

**Comment by alexandrejonathas** [comment]
Oi @geekcom utilizei o método e executei a saída no terminal, o relatório foi gerado com sucesso na pasta de saída.
Comando executado no terminal: 
jasperstarter --locale pt_BR process "C:\dev\workspace\php\fila\public\reports\relatorio\atendimento_sintetico.jasper" -o "C:\dev\workspace\php\fila\public\reports\1576189204_atendimentos_sintetico" -f pdf -P image_url="http://localhost:8000/assets/images/logo.png" data_inicio="2019-01-01" data_fim="2019-01-30" status="CONCLUIDA" -t postgres -H 127.0.0.1 --db-port 5432 -u postgres -p postgres -n consysti_fila --jdbc-dir C:\dev\workspace\php\fila\storage\jdbc

Porém, quando chamo a função execute no php o sistema trava e não responde a mais nenhuma requisição. :(

**Comment by geekcom** [comment]
Como você tá chamando a função? Pode colocar o código por favor?

**Comment by alexandrejonathas** [comment]
Segue o código da chamada: 

```
$input = join(DIRECTORY_SEPARATOR, [public_path('reports'), "relatorio", "atendimento_sintetico.jasper"]);

$output = join(DIRECTORY_SEPARATOR, [public_path(), "reports", time()."_atendimentos_sintetico"]);

        $options = [
            'locale' => 'pt_BR',
            'format' => ['pdf'],
            'params' => [
                'image_url' => $image_url,
                'data_inicio' => date('Y-m-d', strtotime("{$data_inicio}")),
                'data_fim'    => date('Y-m-d', strtotime("{$data_fim}")),
                'status'      => "CONCLUIDA"
            ],
            'db_connection' => $this->connection
        ];

         $report = new PHPJasper();

        $report->process(
            $input,
            $output,
            $options
        )->execute(); //Nesse ponto ele trava, não gera o relatório e não segue a execução do código.
`

**Comment by geekcom** [comment]
@alexandrejonathas alguma novidade nessa issue?

**Comment by alexandrejonathas** [comment]
Sem solução até o momento, grato pela atenção!
