### ISSUE TITLE
Passing an array parameter for java.util.Collection parameter Class

### ISSUE THREAD

**Issue by ikoukuhn** [PHPJasper/phpjasper#206]
I'm trying to pass an array parameter for a collection class parameter but it always give me this error:
**Parameter 'eft_code' of type 'java.util.Collection with value 'B200100002,B200100003' is not supported by JasperStarter!**
Can anyone provide me the right syntax on how to pass an array parameter from this library?
Here's my parameter:

````
"params" = [
    "eft_code" => "B200100002,B200100003"
  ];

$options = [ 
            'format' => ['pdf', 'xls'] ,
            'params' => $params,
            'db_connection' => [
                'driver' => 'postgres', //mysql, ....
                'username' => env('DB_USERNAME'),
                'password' => env('DB_PASSWORD'),
                'host' => env('DB_HOST'),
                'database' => env('DB_DATABASE'),
                'port' => env('DB_PORT')
            ]
        ];

$jasper = new PHPJasper;
        $jasper->process(
            $input,
            $output,
            $options
        )->execute();
````

When I tried those parameter in the iReport directly it works just fine, it's just won't work using PHPJasper...

**Comment by geekcom** [comment]
Hi @ikoukuhn, about your code is ok, but, please check you report to add parameters correctly for example:

```sql
SELECT FISCAL_YEAR,
ACCT_STRUCTURE,
ACCT_REGION,
ACCT_STATUS_CODE,
ACCT_STRUCTURE_DESC
FROM ACCOUNT_STRUCTURE A
WHERE ACCT_REGION IN ($P!{REGION})
AND LOCAL_STATUS = 'O'
```

`$P!{REGION}` is your parameter.
