### ISSUE TITLE
Able to compile but not execute - Exception in JasperPHP.php line 195:

### ISSUE THREAD

**Issue by pmclaughlin17** [PHPJasper/phpjasper#21]
I've installed this and am able to compile reports but when I try to execute them, I get the Error: Exception in JasperPHP.php line 195:

I'm using Laravel 5.1 running on homestead (ubuntu virtualbox)
  Java -version  java version "1.8.0_111"
 Java(TM) SE Runtime Environment (build 1.8.0_111-b14) 
 Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

I created a controller and copied the example code and just hard-coded the path to keep things simple.  The compile method works fine and created a file the "hello_world.jasper" file.  When I try to process that file, I get the error. 

These are the two methods:

    public function compile()
    {
        $input = '/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/examples/hello_world.jrxml';

        $jasper = new JasperPHP;
        $jasper->compile($input)->execute();
    }

    public function process()
    {
        $input = '/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/examples/hello_world.jasper';
        $output = '/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/examples';

        $jasper = new JasperPHP;

        $jasper->process(
            $input,
            $output,
            array("pdf", "rtf")
        )->execute();
    }

I did notice that no matter what I set $input to in the process method, I get the same error.  e.g. $input = 'foo' returns the error.

permissions on the file seem correct
-rwxrwxrwx 1 vagrant vagrant 30082 Dec 17 16:19 hello_world.jasper
-rwxrwxrwx 1 vagrant vagrant 94450 Dec 17 15:59 jasperstarter.exe

When I dump the output I get this:

JasperPHP {#486 ▼
  #executable: "jasperstarter"
  #path_executable: "/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/src/JasperPHP/../JasperStarter/bin"
  #the_command: "./jasperstarter process "/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/examples/hello_world.jasper" -o "/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/examples" -f pdf rtf"
  #redirect_output: true
  #background: true
  #windows: false
  #formats: array:13 [▼
    0 => "pdf"
    1 => "rtf"
    2 => "xls"
    3 => "xlsx"
    4 => "docx"
    5 => "odt"
    6 => "ods"
    7 => "pptx"
    8 => "csv"
    9 => "html"
    10 => "xhtml"
    11 => "xml"
    12 => "jrprint"
  ]
  #resource_directory: "/home/vagrant/Code/riga-app/vendor/geekcom/phpjasper/src/JasperPHP/../../../vendor/geekcom/jasperphp/src/JasperStarter/bin"
}

Any ideas on what I might be doing wrong?

thx

**Comment by geekcom** [comment]
Hi @pmclaughlin17, It looks like it's all right, the only thing I can think of is that you need **777 permission to path/vendor/geekcom/phpjasper/src/JasperStarter/bin**.
I'll simulate your environment and do more testing.

**Comment by pmclaughlin17** [comment]
Hi:
Thanks for looking into this.  The permissions seem correct on that directory (see below).  I'm going to try with a clean install of laravel 5.3 and see if that works and then maybe work back from there.  

cheers

![image](https://cloud.githubusercontent.com/assets/11138769/21352213/7a794ac0-c68e-11e6-98bd-f26278f666bc.png)

**Comment by geekcom** [comment]
hey @pmclaughlin17, it's all right
