### ISSUE TITLE
I can´t install the library with composer

### ISSUE THREAD

**Issue by josevillasmil** [PHPJasper/phpjasper#213]
**Describe the bug**

**To Reproduce**
1. composer require geekcom/phpjasper:
2. Response:
  Using version ^3.3 for geekcom/phpjasper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing geekcom/phpjasper (3.3.1): Downloading (100%)   'C:\xampp\htdocs\sicococloud\vendor/geekcom/phpjasper/d3f043ab13603332c674b58a440e5f7d' is not a zip archive.
 Unzip with ZipArchive class failed, falling back to unzip command
 Failed to download geekcom/phpjasper from dist: Failed to execute unzip -qq -o "C:\xampp\htdocs\sicococloud\vendor/geekcom/phpjasper/d3f043ab13603332c674b58a440e5f7d" -d "C:\xampp\htdocs\sicococloud/vendor/composer/ffbdbc9e"

[C:\xampp\htdocs\sicococloud\vendor/geekcom/phpjasper/d3f043ab13603332c674b58a440e5f7d]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of C:\xampp\htdocs\sicococloud\vendor/geekcom/phpjasper/d3f043ab13603332c674b58a440e5f7d or
        C:\xampp\htdocs\sicococloud\vendor/geekcom/phpjasper/d3f043ab13603332c674b58a440e5f7d.zip, and cannot find C:\xampp\htdocs\sicococloud\vendor/geekcom/phpjasper/d3f043ab13603332c674b58a440e5f7d.ZIP, period.

    Now trying to download from source
  - Installing geekcom/phpjasper (3.3.1): Failed to update https://github.com/PHPJasper/phpjasper.git in cache, package installation for geekcom/phpjasper might fail.
Cloning df25051c1c from cache
    df25051c1c50410d89d51fa84b8b6457b3c1e851 is gone (history was rewritten?)
Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Failed to execute git checkout "df25051c1c50410d89d51fa84b8b6457b3c1e851" -
  - && git reset --hard "df25051c1c50410d89d51fa84b8b6457b3c1e851" --

  fatal: reference is not a tree: df25051c1c50410d89d51fa84b8b6457b3c1e851

**Expected behavior**
A full package installed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: windows7 32bits
 - Browser:chrome
 - console: git bash

**Additional context**
No further more

**Comment by geekcom** [comment]
Hi @josevillasmil, please check you PHP installation, you need to have the zip extension.

**Comment by josevillasmil** [comment]
Thanks, but its already installed correctly
