### ISSUE TITLE
preview the pdf before downloading

### ISSUE THREAD

**Issue by rodrigodevts** [PHPJasper/phpjasper#215]
Hello.
I am using phpjasper, and it is downloading the pdf correctly, however, I would like to know if it is possible to view the pdf in the browser before downloading.
If possible, I wanted to know how.
Sorry for my English, I only know the basics.

**Comment by geekcom** [comment]
Hi @rodrigodevelop-tech , in your report controller can you try something like this?

```php
private function viewReportOnBrowser($output, $extension, $filename)
    {
        header('Content-Description: application/pdf');
        header('Content-Type: application/pdf');
        header('Content-Disposition:; filename=' . $filename . '.' . $extension);
        readfile($output . '.' . $extension);
        unlink(dirname($output) . '/' . $filename . '.' . $extension);
        flush();
        return;
    }
```

**Comment by rodrigodevts** [comment]
Hi, thanks for answering me.
What would the $extension variable be? 
 ```
$input = __DIR__ . '/Honorario.jasper';  
$output = '';    
$jdbc_dir = 'C:/xampp/htdocs/teste/vendor/geekcom/phpjasper/bin/jasperstarter/jdbc';
$options = [ 
    'format' => ['html'],
    'db_connection' => [
        'driver' => 'generic', 
        'username' => 'SYSDBA',
        'password' => '',
        'host' => '127.0.0.1',
        'database' => 'faturaandro',
        'port' => '3050',
        'jdbc_driver' => 'org.firebirdsql.jdbc.FBDriver',
        'jdbc_url'    => 'jdbc:firebirdsql:127.0.0.1/3050:faturaandro',
        'jdbc_dir'  => $jdbc_dir 
    ] 
];

$jasper = new PHPJasper;
$jasper->viewReportOnBrowser($output,$options,$input);
```
When performing the test in the browser, it displays the error message: "Failed to load PDF document".

**Comment by rodrigodevelop-tech** [comment]
> Hi @rodrigodevelop-tech , in your report controller can you try something like this?
> 
> ```
> private function viewReportOnBrowser($output, $extension, $filename)
>     {
>         header('Content-Description: application/pdf');
>         header('Content-Type: application/pdf');
>         header('Content-Disposition:; filename=' . $filename . '.' . $extension);
>         readfile($output . '.' . $extension);
>         unlink(dirname($output) . '/' . $filename . '.' . $extension);
>         flush();
>         return;
>     }
> ```

**Comment by geekcom** [comment]
PDF
