### ISSUE TITLE
Bug with INSERT, UPDATE OR DELETE

### ISSUE THREAD

**Issue by tauanmarcel** [PHPJasper/phpjasper#216]
Hello!
I have a problem running the report. I'm using a procedure to get the data but I noticed that when there is an INSERT, UPDATE OR DELETE in the procedure, PHPJasper cannot generate the report. It can generate .jasper but cannot execute it. In command line only returns the following error: **_Error filling reportError executing SQL statement for: myReport._**
The procedure is correct because it works in DBeaver and also in Jasper Studio.
When there is no INSERT, UPDATE OR DELETE, it works normally.
Would anyone know how to fix this problem?

**Comment by geekcom** [comment]
we didn't have any bugs related to that

**Comment by tauanmarcel** [comment]
I think it may be the driver (com.microsoft.sqlserver.jdbc.SQLServerDriver), but I still don't know how to fix it.
Another point is that PHPJasper is running on windows server 2003 with java 1.7, I tried to upgrade to 1.8 but win 2003 is not supported

**Comment by tauanmarcel** [comment]
If anyone has the same problem, I am using PHP Jasper version 1.16 and was using the sqljdbc41 driver. The problem was exactly in the driver, if you have the same problem, try a mssql-jdbc-7.2.2.jre8 version and it will probably fix the problem.
