### ISSUE TITLE
Can´t run using docker

### ISSUE THREAD

**Issue by erikafcf** [PHPJasper/phpjasper#217]
I'm trying to use the library with docker but I'm always getting the error **Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.** when I try to run the report.

To install the library I included the `"geekcom/phpjasper": "^3.2.0"` command in the composer.json file and ran `docker-compose exec app composer install `. The vendor / geekcom / ... folder is created without any problems.

 I run **docker-compose up -d** and get the message
**baseapp is up-to-date
baseweb is up-to-date**

When I try to run the **docker exec -it phpjasper composer install command**, the error "**Error: No such container: phpjasper"** occurs.

I included 
```
RUN chmod 777 /var/www/vendor/geekcom/phpjasper/bin/jasperstarter/bin
RUN chmod 777 /var/www/vendor/geekcom/phpjasper/src/JasperStarter/bin/jasperstarter
```
commands in the app.dockerfile file to avoid permission problems that I read that could be the possible cause.

I created the route `Route::get('/relatorio','ReportController@index');` in the api.php file and created the ReportController file with the index method with the code

```
 public function index() {
        $jasper = new PHPJasper;
        $input = '/var/www/vendor/geekcom/phpjasper/examples/hello_world.jrxml';
        $output = '/var/www/vendor/geekcom/phpjasper/examples';

        $options = [
            'format' => ['pdf', 'rtf']
        ];

        $jasper->process(
            $input,
            $output,
            $options
        )->execute();

    }
```

When I change the execute to output the text returned is
**./jasperstarter process "/var/www/vendor/geekcom/phpjasper/examples/hello_world.jrxml" -o "/var/www/vendor/geekcom/phpjasper/examples" -f pdf rtf**

What can I be doing wrong?

**Comment by geekcom** [comment]
Hi @erikafcf, please run your command:

**./jasperstarter process "/var/www/vendor/geekcom/phpjasper/examples/hello_world.jrxml" -o "/var/www/vendor/geekcom/phpjasper/examples" -f pdf rtf**

in the folder:

`/var/www/vendor/geekcom/phpjasper/bin/jasperstarter/bin`

and see the return.

**Comment by erikafcf** [comment]
Hi, @geekcom 
I don't know how to run a command 'inside' the docker. Could you explain how to do it?
By running the command below (with the absolute path), the .pdf and .rtf files are generated.

```
PS C:\workspace-phpjasper\scjf-api\vendor\geekcom\phpjasper\bin\jasperstarter\bin> ./jasperstarter process "C:/workspace-phpjasper/scjf-api/vendor/geekcom/phpjasper/examples/hello_world.jrxml" -o "C:/workspace-phpjasper/scjf-api/vendor/geekcom/phpjasper/examples/" -f pdf rtf        
PS C:\workspace-phpjasper\scjf-api\vendor\geekcom\phpjasper\bin\jasperstarter\bin> 
```

**Comment by erikafcf** [comment]
@geekcom,
I managed to run the command inside the docker.Error:  java: not found
![image](https://user-images.githubusercontent.com/60197040/81586318-b5ea7480-938b-11ea-864a-1199dbcd30d8.png)

**Comment by erikafcf** [comment]
@geekcom,
I managed to run the command inside the docker.Error:  java: not found
![image](https://user-images.githubusercontent.com/60197040/81586556-0cf04980-938c-11ea-9751-2805d8db4c5b.png)

**Comment by geekcom** [comment]
so... @erikafcf do you need to install Java JDK..

Requirements for PHPJasper:

- PHP 7.2 or above
- Java JDK 1.8

Thanks for use this lib.

**Comment by erikafcf** [comment]
@geekcom, last question (I hope)
Which docker image did you use to run the program?
I'm using FROM php:7.2-fpm but I'm having trouble installing jdk.

**Comment by geekcom** [comment]
Hi @erikafcf i use https://github.com/PHPJasper/dockerizer, thanks for your questions.
