### ISSUE TITLE
Write unit tests for each method.

### ISSUE THREAD

**Issue by geekcom** [PHPJasper/phpjasper#23]
Methods:
- compile
- process
- listParameters
- output
- execute

**Comment by nagbhushan** [comment]
Dear GeekCom,

I tried running the script and got below error....

Fatal error: Uncaught exception 'Exception' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.' in /Applications/XAMPP/xamppfiles/htdocs/jasper/vendor/geekcom/phpjasper/src/JasperPHP/JasperPHP.php:205 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/jasper/index.php(10): JasperPHP\JasperPHP->execute() #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/jasper/vendor/geekcom/phpjasper/src/JasperPHP/JasperPHP.php on line 205

/bin/jasperstarter command complies .jrxml to .jasper from command line but not from php's exec().

Any directions would be much appreciated. I am testing on mac.

Below in exec()

./jasperstarter compile "/Applications/XAMPP/xamppfiles/htdocs/jasper/vendor/geekcom/phpjasper/examples/hello_world.jrxml"

Thank you.
