### ISSUE TITLE
Centos8 generating empty reports

### ISSUE THREAD

**Issue by juanadamuzsimj** [PHPJasper/phpjasper#265]
**Describe the bug**
I have been testing in a windows environment and everything was ok. I switched to Centos8 and my PDF pages are empty.

Centos8 java version:

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**To Reproduce**
1. List jrxml parameters
2. Fill parameters array
3. Process file
4. Execute file

**Expected behavior**
Pdf with my information as in windows does correctly
**Screenshots**
![image](https://user-images.githubusercontent.com/61426384/96859498-daca3400-1461-11eb-8bba-b141c2cba77b.png)

**Desktop (please complete the following information):**
 - OS: Centos8
 - Version 3.3.1

**Comment by juanadamuzsimj** [comment]
I've been looking for a solution and some people discovered is something related to the data source. If i remove the "-t" param and "--data-file" param, the report renders ok without data obviously.

**Comment by waresz** [comment]
PHPJasper did not update the source anymore: I attach an update.

PJPJasper with jasper 12.0:

http://www.mediafire.com/file/rkn57xbpnvmrd5a/PHPJasper.zip/file

**Comment by juanadamuzsimj** [comment]
I've figured out that the problem was an empty dataset. Whenever tmy json was empty due to 0 records all page display white... I'll try the version you sent me. Thanks!
