### ISSUE TITLE
não retorna dados do banco com PHPJasper 

### ISSUE THREAD

**Issue by cadufavaro** [PHPJasper/phpjasper#277]
Estou criando o relatório com o jasper studio e passando parâmetros inclusive da condição SQL.

Meu código:

require DIR . '/vendor/autoload.php';

use PHPJasper\PHPJasper;

$input = DIR. '/reports/report.jrxml';

$jasper = new PHPJasper;

$output = DIR . '/file/doc';
$options = [
    'format' => ['pdf'],
    'params' => [
        'ID' => 50,
        'TITULO' => 'Meu Relatório'
    ],
    'db_connection' => [
        'driver' => 'mysql', //mysql, ....
        'username' => 'user',
        'password' => '*****',
        'host' => 'localhost',
        'database' => 'meubd',
        'port' => '3306',
        'jdbc_driver' => 'com.mysql.jdbc.Driver',
        'jdbc_url' => 'jdbc:mysql://localhost:3306;databaseName=seedbd',
        'jdbc_dir' => DIR. '/vendor/geekcom/phpjasper/bin/jasperstarter/jdbc/mysql-connector-java-5.1.48.jar'
    ]
];

$jasper->process(
        $input,
        $output,
        $options
)->execute();

$filename = 'doc.pdf';
header('Content-Description: application/pdf');
header('Content-Type: application/pdf');
header('Content-Disposition:; filename=' . $filename);
readfile(DIR . '/file/' . $filename);
flush();

ele retorna o relatório sem os dados do banco que era para ter sido pesquisado pelo ID, o campo TITULO exibe normal.
dando um print ele me retorna: 

jasperstarter process "DIR/report.jrxml" -o "DIR/file/doc" -f pdf -P ID="50" TITULO="Meu Relatório" -t mysql -u user -p ***** -H localhost -n meubd --db-port 3306 --db-driver com.mysql.jdbc.Driver --db-url jdbc:mysql://localhost:3306;databaseName=meubd --jdbc-dir DIR/src/library/vendor/geekcom/phpjasper/bin/jasperstarter/jdbc/mysql-connector-java-5.1.48.jar

pode me ajudar?

**Comment by geekcom** [comment]
**pt-BR**

Olá @cadufavaro, este exemplo que você está usando, funciona apenas para conexões com banco de dados Microsoft SQL, como consta na doc [aqui](https://github.com/PHPJasper/phpjasper#using-mssql-database), por favor confira os exemplos [aqui](https://github.com/PHPJasper/examples).

**en**
Hello @cadufavaro, this example you are using, works only for connections to Microsoft SQL database, as shown in the doc [here](https://github.com/PHPJasper/phpjasper#using-mssql-database), please check the examples [here](https://github.com/PHPJasper/examples)
