### ISSUE TITLE
No secret found for "" key in "net.sf.jasperreports.data.adapter" category

### ISSUE THREAD

**Issue by gamelabid** [PHPJasper/phpjasper#280]
Hi, i'm using PHPJasper to generate report using Jasper Report + PHP.
Previewing & Generating PDF in Jasper Report itself works well, but unfortunately when i'm trying to generate the PDF from my site, it returned this error (after i try to run the code generated from the website into the terminal of course) :

`No secret found for "" key in "net.sf.jasperreports.data.adapter" category`

How can i solve this? Thanks in advance

**Comment by geekcom** [comment]
Please see: 
https://stackoverflow.com/questions/49692496/jasper-no-secret-found-for-xxxxx-key-in-net-sf-jasperreports-data-adapter/49817393#49817393
