### ISSUE TITLE
Pass PHP Array to Jasper Report then Iterate it

### ISSUE THREAD

**Issue by gamelabid** [PHPJasper/phpjasper#281]
I want to pass my parameter that is in Array form, then iterate it in Jasper Report.
What class/type of parameter should i determine in Jasper Report so the param can accept PHP Array?

How can i achieve this?
Thanks in advance, i need to solve this in a hurry.

**Comment by geekcom** [comment]
Please see this example:

https://github.com/PHPJasper/phpjasper#using-database-to-generate-reports
