### ISSUE TITLE
Problem on connecting with Mysql 8 

### ISSUE THREAD

**Issue by elton182** [PHPJasper/phpjasper#287]
Using driver generic with mysql 8 was not working, so I've had to change the mysql driver to mysql-connector-java-8.0.24.

The JDBC Class is com.mysql.cj.jdbc.Driver

**Comment by geekcom** [comment]
Thanks @elton182, in this case, just download the driver and put it in the folder `bin/jasperstarter/jdbc`

**Comment by elton182** [comment]
I download the driver and put it on my project repository on a specific folder.
The good thing is that we can pass the path to the driver folder as a parameter.

**Comment by elton182** [comment]
By the way, it may be a good thing to add this to the documentation
