### ISSUE TITLE
erro ao gerar o relatório

### ISSUE THREAD

**Issue by Danillosdd** [PHPJasper/phpjasper#288]
Ao chamar o arquivo relatorio.php?parametro=48 para gerar o pdf retornar no browser, o erro:

Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /opt/NetMake/v9-php73/wwwroot/scriptcase/app/viniciuscontabilidade/relatorio/vendor/geekcom/phpjasper/src/PHPJasper.php:221 Stack trace: #0 /opt/NetMake/v9-php73/wwwroot/scriptcase/app/viniciuscontabilidade/relatorio/relatorio.php(63): PHPJasper\PHPJasper->execute() #1 {main} thrown in /opt/NetMake/v9-php73/wwwroot/scriptcase/app/viniciuscontabilidade/relatorio/vendor/geekcom/phpjasper/src/PHPJasper.php on line 221

**Comment by Danillosdd** [comment]
meu arquivo relatório.php esta assim:

```<?php



require __DIR__ . '/vendor/autoload.php';



use PHPJasper\PHPJasper;    

$parametro = $_GET['parametro'];

$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/relatorio.jrxml';   

$output = __DIR__ . '/vendor/geekcom/phpjasper/examples/relatorio-'.$parametro.'';



$options = [

    'format' => ['pdf'],

    'locale' => 'pt_BR',

    'params' => [

         'parametroprincipal' => $parametro,

    ],

    'db_connection' => [

        'driver' => 'postgres',

        'username' => 'postgres',

        'password' => '123456',

        'host' => 'localhost',

        'database' => 'teste',

        'port' => '5432'

    ]

];



$jasper = new PHPJasper;



$jasper->process(

        $input,

        $output,

        $options

)->execute
();



//	AQUI VOCÊ COLOCA O CÓDIGO PARA EXIBIR NO BROWSER.


$file = __DIR__ . '/vendor/geekcom/phpjasper/examples/relatorio-'.$parametro.'.pdf'; 


$filename = 'relatorio-'.$parametro.'.pdf'; /* Note: Always use .pdf at the end. */





header('Content-type: application/pdf');


header('Content-Disposition: inline; filename="' . $filename . '"');


header('Content-Transfer-Encoding: binary');


header('Content-Length: ' . filesize($file));


header('Accept-Ranges: bytes');



@readfile($file);



//	EXEMPLO EM PYTHON:

//		https://github.com/PyReportJasper/pyreportjasper#flask-example



?>```

**Comment by Danillosdd** [comment]
Se eu executo no terminal o comando abaixo o pdf é gerado com sucesso, mais ao chamar pelo relatório.php no browser ocorre o erro mencionado.

```./jasperstarter process "/relatorio/vendor/geekcom/phpjasper/examples/relatorio.jasper" -o "/relatorio/vendor/geekcom/phpjasper/examples" -f pdf```

**Comment by Danillosdd** [comment]
@jadsonbr

**Comment by jadsonbr** [comment]
@Danillosdd 
O erro informado geralmente é ocasionado pelo caminho do arquivo `.jrxml` inválido, como você pode ver [aqui no código de validação da linha 221 da biblioteca](https://github.com/PHPJasper/phpjasper/blob/master/src/PHPJasper.php#L221)

Provavelmente funcionou ao executar o básico pelo terminal por ter passado o caminho correto.
Verifique isso é nos dê um feedback.

**Comment by Danillosdd** [comment]
@jadsonbr Verifiquei o caminho do input e esta correto, o arquivo do `.jrxml `esta neste diretório.

**Comment by Danillosdd** [comment]
Creio que seja permissão, estou usando Ubuntu, e acho que dei permissão correto na pasta, pois dei um `sudo chmod 777 -R` na pasta do relatório

**Comment by jadsonbr** [comment]
@Danillosdd qual versão da biblioteca está utilizando ?

**Comment by Danillosdd** [comment]
@jadsonbr  Aonde verifico esta informação?

**Comment by Danillosdd** [comment]
Observação ao subir no xampp no windows da certo, o problema é no linux; por isso que eu acho que é problema de permissão

**Comment by Danillosdd** [comment]
O Problema é o apache do scriptcase do meu ambiente de desenvolvimento, pois ao executar em outro apache gerou com sucesso; verifiquei os arquivos conf do apache do scriptcase e fiz  a liberação do pgsql(Pois estou usando Postgres), e deu certo.
