### ISSUE TITLE
Feature Request: Support for resource option

### ISSUE THREAD

**Issue by Aterbonus** [PHPJasper/phpjasper#30]
jasperstarter has a [resource option](http://jasperstarter.cenote.de/usage.html#Reports_with_resources)

In my particular case I need to specify this option when I have a report with a subreport, otherwise jasperstarter throws an exception ```Error filling reportResource not found at: subreport_file.jasper.```

As I have the subreport file in the same directory as the main report, I just need to add ```-r``` at the end of the command string, but if the subreport file exists in other directory we need to specify it like ```-r other/directory/```

**Comment by geekcom** [comment]
Thanks @Aterbonus, great idea

**Comment by geekcom** [comment]
Solved, thanks @Aterbonus for open this issue.

https://github.com/PHPJasper/phpjasper/releases/tag/v2.2
