### ISSUE TITLE
Bug With laravel 5.3

### ISSUE THREAD

**Issue by talenta-eg** [PHPJasper/phpjasper#32]
Thanks for this Awesome API , i follow your guide in installation with larave but when call `http://localhost:8000/reports`

i found this error 
`Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.`

**Could you help please**

**Comment by geekcom** [comment]
Hello @3a6ala, just run output(), and check and show me the return, below is the complete example code.

`
    require __DIR__ . '/vendor/autoload.php';

    use JasperPHP\JasperPHP;

    $input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jasper';  
    $output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    

    $jasper = new JasperPHP;

    print $jasper->process(
    $input, //input
    $output, //output
    ['pdf', 'rtf'], //formats
    [],    //parameters
    [],    //data_source
    'en'   //locale
    )->output();`

**Comment by talenta-eg** [comment]
`./jasperstarter --locale en process "/home/muhammadatallah/Code/bpm-application/routes/vendor/geekcom/phpjasper/examples/hello_world.jasper" -o "/home/muhammadatallah/Code/bpm-application/routes/vendor/geekcom/phpjasper/examples" -f pdf rtf`

**This is The return of code***

**Comment by geekcom** [comment]
//Advanced example - using a database

    require __DIR__ . '/vendor/autoload.php';

    use JasperPHP\JasperPHP;

    $input = __DIR__ . '/input/teste.jrxml';
    $output = __DIR__ . '/output';
    $options = [
    'format' => ['pdf', 'xml', 'html'],
    'locale' => 'en',
    'params' => [],
    'db_connection' => [
        'driver' => 'postgres',
        'username' => 'postgres',
        'password' => '123456',
        'host' => 'localhost',
        'database' => 'teste',
        'schema' => 'public',
        'port' => '5432'
    ]
    ];

This example is ok.
