### ISSUE TITLE
Laravel Support Note: PHPJasper Can be used regardless of your PHP Framework

### ISSUE THREAD

**Issue by geekcom** [PHPJasper/phpjasper#35]
Until the release 1.12

* Laravel Facades support - removed

**Comment by jilvanx** [comment]
This package works on Laravel 5.4?

**Comment by geekcom** [comment]
Yes @jilvanx, 
**PHPJasper Can be used regardless of your PHP Framework**

**Comment by geekcom** [comment]
Sorry @jilvanx, excludes your message by accident

**Comment by sathya26** [comment]
how do return arrays for jrxml
