### ISSUE TITLE
Suporte ao Oracle -  Oracle Support

### ISSUE THREAD

**Issue by fcoassis** [PHPJasper/phpjasper#42]
Há alguma previsão, ou intenção, para suporte ao Oracle? Parabéns pelo trabalho!

Are there any predictions, or intentions, for Oracle support? Congrats on the job!

**Comment by jeffbarreto** [comment]
Obrigado pela idéia @fcoassis, vou analisar a possibilidade dessa implementação.

**Comment by geekcom** [comment]
Obrigado pela ideia @fcoassis, vou analisar como fazer essa implementação.

Thanks @fcoassis , I'll analyze how to do this implementation.

**Comment by jadsonbr** [comment]
Faça o download do jar do JDBC específico para a sua versão do Banco.
[JDBC Driver Oracle](http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-112010-090769.html)

Coloque o jar baixado no diretório PastaDoSeuProjeto/vendor/geekcom/phpjasper/bin/jasperstarter/jdbc/

E detalhes sobre o que passar na url você pode encontrar no link abaixo:
[Data Sources and URLs](http://docs.oracle.com/cd/B28359_01/java.111/b31224/urls.htm)
