### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by pedroaugustoneto** [PHPJasper/phpjasper#43]
Apenas segui os passos do Readme, mas gera o seguinte erro:

Fatal error: Uncaught JasperPHP\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /Applications/XAMPP/xamppfiles/htdocs/g2city/vendor/geekcom/phpjasper/src/JasperPHP.php:198 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/g2city/index.php(10): JasperPHP\JasperPHP->execute() #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/g2city/vendor/geekcom/phpjasper/src/JasperPHP.php on line 198

**Comment by geekcom** [comment]
Olá @pedroaugustoneto por favor "rode" o método `output()` para verificar o comando que está sendo gerado na saída, confira também os caminhos dos arquivos, abaixo um exemplo de como executar o método `output()`.

Hello @pedroaugustoneto please run the `output ()` method to check the command, check out the file paths, below an example of how to execute the `output ()` method.

```php
require __DIR__ . '/vendor/autoload.php';

use JasperPHP\JasperPHP;

$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jasper';  
$output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    
$options = [ 
    'format' => ['pdf', 'rtf'] 
];

$jasper = new JasperPHP;

echo 
    $jasper->process(
    $input,
    $output,
    $options
)->output();
```

**Comment by pedroaugustoneto** [comment]
Fiz com o código que pediu:

./jasperstarter process "/Applications/XAMPP/xamppfiles/htdocs/g2city/vendor/geekcom/phpjasper/examples/hello_world.jasper" -o "/Applications/XAMPP/xamppfiles/htdocs/g2city/vendor/geekcom/phpjasper/examples" -f pdf rtf

Estou utilizando um Mac, também realizei as permissões.

**Comment by jadsonbr** [comment]
```php

require __DIR__ . '/vendor/autoload.php';

use JasperPHP\JasperPHP;

// Na linha abaixo utilize o .JRXML ao invés do .JASPER
$input = __DIR__ . '/vendor/geekcom/phpjasper/examples/hello_world.jrxml';
$output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    
$options = [ 
    'format' => ['pdf', 'rtf'] 
];

$jasper = new JasperPHP;

echo 
    $jasper->process(
    $input,
    $output,
    $options
)->output();
```
Verifique também a versão do JDK instalado nos S.O.
