### ISSUE TITLE
Parâmetro em condição "IN"

### ISSUE THREAD

**Issue by jaisson** [PHPJasper/phpjasper#55]
Primeiramente, meus parabéns pelo projeto, encontrei ele no GitHub e realmente ele está sendo de grande ajuda para as minhas aplicações.
Tenho algumas duvidas com relação ao envio de parâmetros em lista, por exemplo quero obter informações da minha tabela utilizando o operados "IN",
mas não estou conseguindo fazer funcionar.
Trecho do meu sql:
`WHERE PROJETO.ID IN ($P{idProjeto})`
Trecho do meu PHP:
`$options = [
  'format' => ['pdf'],
  'params' => ['projetoID'=>"'1,2,3'"],
  'db_connection' => [...]
];`

**Comment by jadsonbr** [comment]
Tente da seguinte maneira.
Pelo que eu entendi o nome do seu parâmetro no relatório é **idProjeto** e não **projetoID**. 
E sem as aspas simples no parametro **idProjeto**. Pois se ele estiver assim **'1,2,3'** para o banco será um único valor com os caracteres **1,2,3** e não três valores como você deseja.
```php
$options = [ 'format' => ['pdf'], 'params' => ['idProjeto'=>"1,2,3"], 'db_connection' => [...] ];
```

**Comment by viniciuspasini** [comment]
**Estou com problema em enviar os parâmetros em lista. No meu caso estou tentando passar um array nos parâmetros:**
```
Array ( 
    [nome_fantasia] => CONSUMIDOR 
    [endereco] => TESTE [
    telefone] => 12121212 
    [status] => true 
    [empresa] => Array ( [0] => Empresa Template [1] => Toca do lobo [2] => Suspire Doces e Sorvetes ) 
)
```
**Query:**
```
SELECT pessoa.*, empresa.nome_fantasia 
FROM cadastro.pessoa
inner join cadastro.empresa on pessoa.id_empresa = empresa.id
WHERE (cadastro.pessoa.nome_fantasia = $P{nome_fantasia} OR $P{nome_fantasia} IS NULL) 
	  AND (cadastro.pessoa.endereco = $P{endereco} OR $P{endereco} IS NULL)
	  AND (cadastro.pessoa.fone1 = $P{telefone} OR $P{telefone} IS NULL)
	  AND (cadastro.pessoa.status = $P{status}  OR $P{status} IS NULL)
	  AND ($X{IN,  empresa.nome_fantasia, empresa})
```

Codigo:
```
$input = __DIR__ . '/relatorio/ralacaoClientes.jrxml';
$output = __DIR__ . '/relatorio/pdf';
$inputJasper = __DIR__ . '/relatorio/ralacaoClientes.jasper';
$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => $param, //Array com os parâmetros
    ....
```
O metódo output() esta Retornando isso: 
jasperstarter --locale pt_BR process "F:\37\Web\sistema\notafacil\vinicius\sistema\relatorios\clientes/relatorio/ralacaoClientes.jasper" -o "F:\37\Web\sistema\notafacil\vinicius\sistema\relatorios\clientes/relatorio/pdf" -f pdf -P nome_fantasia="CONSUMIDOR" endereco="TESTE" telefone="12121212" status="true" **empresa="Array"** -t postgres -u postgres -p dw91v2m300 -H 192.168.1.37 -n db_solidos --db-port 5030

o parâmetro [empresa] esta retornando apenas "array", como faço pra resolver isso, tem uma forma mais simples de passar uma lista de valores pra um parâmetro?

**Comment by geekcom** [comment]
Olá @viniciuspasini, se a resposta resolveu seu problema por favor feche a issue.

Hello @viniciuspasini, if the answer solves your problem please close this issue.
