### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';'

### ISSUE THREAD

**Issue by Dericktan** [PHPJasper/phpjasper#6]
Hi, i got an error:

`PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in C:\Bitbucket\testJasper\vendor\lavela\phpjasper\src\JasperPHP\JasperPHP.php on line 8`

**Comment by geekcom** [comment]
Hi @Dericktan, which your operating system?

**Comment by Dericktan** [comment]
Windows 10 Home 64-Bit (10.0, Build 14393)

**Comment by geekcom** [comment]
Please reinstall your Java JDK 1.8, and try.
