### ISSUE TITLE
Oracle support?

### ISSUE THREAD

**Issue by vbspcoder** [PHPJasper/phpjasper#61]
$jdbc_dir = __DIR__ . '/vendor/geekcom/phpjasper/bin/jaspertarter/jdbc';
$options = [
    'format' => ['pdf'],
    'locale' => 'en',
    'params' => [],
    'db_connection' => [
        'driver' => 'generic',
        'host' => '127.0.0.1',
        'port' => '1433',
        'database' => 'DataBaseName',
        'username' => 'UserName',
        'password' => 'password',
        'jdbc_driver' => 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
        'jdbc_url' => 'jdbc:sqlserver://127.0.0.1:1433;databaseName=Teste',
        'jdbc_dir' => $jdbc_dir
    ]

how to config connection to connect to oracle?

**Comment by geekcom** [comment]
You need to download the jdbc driver for your database, for example:

http://www.oracle.com/technetwork/apps-tech/jdbc-112010-090769.html

and paste at vendor/geekcom/bin/jasperstarter/jdbc/

**Comment by geekcom** [comment]
http://docs.oracle.com/cd/B28359_01/java.111/b31224/urls.htm
