### ISSUE TITLE
jasperphp run in terminal but not in browser

### ISSUE THREAD

**Issue by freebornforever** [PHPJasper/phpjasper#62]
I've created a test file and try to run but unfortunately it didn't work, here is the error message

Fatal error: Uncaught JasperPHP\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /var/www/html/vendor/geekcom/phpjasper/src/JasperPHP.php:198 Stack trace: #0 /var/www/html/test.php(14): JasperPHP\JasperPHP->execute() #1 {main} thrown in /var/www/html/vendor/geekcom/phpjasper/src/JasperPHP.php on line 198

When I ran in terminal, it's OK, I've searched Internet and most answer is write permission problem,
so I ran bash script as following

sudo chmod 777 -R /var/www/html

so I'm sure that the folder is writable but wonder why it was unable to run in browser.

Please let me know how to solve.

Thanks in advance

**Comment by freebornforever** [comment]
I edited source code to show error number and it was ERROR 127.

**Comment by freebornforever** [comment]
PROBLEM SOLVED!

I have installed JDK in home directory therefore jasperstarter had no permission to run JAVA.
That's why I's able to run in terminal but not browser because browser using www-data 
which no permission in my home directory.

**Comment by yientau** [comment]
I am getting the same error. I am using XAMPP on Mac. Can you elaborate about the permission issue and how did you fix it? I can run the command successfully from terminal, but not able to run it on browser too. How do I give permission to the daemon? and I doubt my issue has to do with Java permission.

**Comment by adummy832** [comment]
@freebornforever , Dude how did you resolve this issue? Been facing the same on my linux machine.

**Comment by adummy832** [comment]
@yientau, 2years have already been passed did u resolve this issue bro? Been facing the same. 😫

**Comment by freebornforever** [comment]
> @yientau, 2years have already been passed did u resolve this issue bro? Been facing the same.

Did you read my prior post before asking?
I have posted clearly how to solve the problem, if you still do not understand read it again and again.

**Comment by wiltonbarros** [comment]
@freebornforever, i have the same error. How you resolved this?

**Comment by wiltonbarros** [comment]
@adummy832 did you have resolve this?

**Comment by jer0256** [comment]
@wiltonbarros hi did you resolve this?

**Comment by tonyyer** [comment]
estimados, alguien logro solucionar ese problema , solo carga en el terminal mas no desde php usando PHPjasper
