### ISSUE TITLE
Use different output file name

### ISSUE THREAD

**Issue by yientau** [PHPJasper/phpjasper#87]
Hi,
Is there any way I can use a different output file? I need to output file to be named differently on every report generation. For example prefix with datetime.

**Comment by geekcom** [comment]
Hi @yientau, see this example:
`$reportName = time() . '_report.pdf';`

**Comment by yientau** [comment]
Where do I set the $reportName to?

**Comment by larry852** [comment]
Hi @yientauset, set file name in $output variable.

`$output = __DIR__ . '/reports/filename';`

this generate the file.

`reports/filename.pdf
`

[http://jasperstarter.cenote.de/usage.html](url)
