### ISSUE TITLE
Documentation rework... README.md

### ISSUE THREAD

**Issue by geekcom** [PHPJasper/phpjasper#9]
lets go...

**Comment by Wferr** [comment]
Would using github wiki for moving, reworking and debloating the readme / documentation file work? If so ill take this up.

**Comment by richa-coder** [comment]
Is this taken up by someone? can i work on it?

**Comment by geekcom** [comment]
Yes @richa-coder

**Comment by geekcom** [comment]
Yes, go @Wferr

**Comment by richa-coder** [comment]
hey,what kind of changes are you actually looking for in the doc?

**Comment by geekcom** [comment]
Really, @richa-coder, i'm need you to be improved, so it is easier to read.

**Comment by richa-coder** [comment]
ya i guess that's too much to read,i can simplify it .just the explanation
of the commands, the errors and compilation steps. will it be fyn? or u
need anything else?

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

On 18 October 2016 at 09:37, Daniel Rodrigues Lima <notifications@github.com

**Comment by geekcom** [comment]
at the moment is just that @richa-coder

**Comment by richa-coder** [comment]
okay,today itself i will start working on it.

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

On 18 October 2016 at 16:29, Daniel Rodrigues Lima <notifications@github.com

**Comment by geekcom** [comment]
ok @richa-coder , thanks XD

**Comment by richa-coder** [comment]
My pleasure :)

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links

On 18 October 2016 at 17:23, Daniel Rodrigues Lima <notifications@github.com

**Comment by SilentFlame** [comment]
Is it available to work on?

**Comment by geekcom** [comment]
yes @SilentFlame

**Comment by puranik9** [comment]
hi i would like to work on this if it is still available

**Comment by geekcom** [comment]
yes @puranik9 , go
