### ISSUE TITLE
VERSION JASPER PHP 7.1.*

### ISSUE THREAD

**Issue by miguelhangelh** [PHPJasper/phpjasper#91]
there is a comment that went down to 7.0
But in the tutorial it asks for php 7.1 higher
Does jasphp work with 7.1 or 7.0?
Is that I work with LARAVEL 5.5 and php 7.1.8

Sorry for my english, I use google

**Comment by geekcom** [comment]
Hi @MiguelHAngelH, the requiremens is:

- PHP 7.0 or above
- Java JDK 1.8

-----

**Comment by miguelhangelh** [comment]
Thanks!!
