### ISSUE TITLE
Open PDF directly in web browser inseatd of save PDFfile

### ISSUE THREAD

**Issue by harvy76** [PHPJasper/phpjasper#93]
Hello,
I would like to ask you, is it possible open the generated file in wib browser instead of save PDF file into filesystem? For example generate it via TFPDF.
Please, can you help me with it?

Thank you
Honza H

**Comment by geekcom** [comment]
Hey @harvy76 see my solution for this problem:

```php
private function viewReport($output, $ext, $filename)
{
    header('Content-Description: application/pdf');
    header('Content-Type: application/pdf');
    header('Content-Disposition:; filename=' . $filename . '.' . $ext);
    readfile($output . '.' . $ext);
    unlink(dirname($output) . '/' . $filename .  '.'  . $ext);
    flush();
    
    return;
}
```

**Comment by hondaman900** [comment]
I'm trying to use this example to launch the  PDF created from PHPjasper, but from the above snippet I can't figure out where to place this code. I'm trying to use it in a <?php> section in my blade but it's crashing the page. Can you please point me in the right direction, or is there a filly-worked example I can follow?
