### ISSUE TITLE
Problemas no PHP 7.0

### ISSUE THREAD

**Issue by luisfwermann** [PHPJasper/phpjasper#97]
Olá, estou utilizando a biblioteca e estou com problemas no PHP 7.0.

Utilizo Ubuntu 14.04, e estava com o PHP 5.5.9 e Java 7. Atualizei ambos para 7.0 e 8:
`root@jonas:/home/solis# java -version`
`java version "1.8.0_161"`
`Java(TM) SE Runtime Environment (build 1.8.0_161-b12)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)`

`root@jonas:/home/solis# php -version`
`PHP 7.0.28-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:05:05) ( NTS )`
`Copyright (c) 1997-2017 The PHP Group`
`Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies`
`    with Zend OPcache v7.0.28-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies`

E quando tento utilizar o PHPJasper recebo este erro: 
'PHP Catchable fatal error:  Argument 1 passed to PHPJasper\\PHPJasper::process() must be an instance of PHPJasper\\string, string given, called in /var/www/authpro/module/Common/src/Common/V1/Rest/JasperReport/JasperReportResource.php on line 42 and defined in /var/www/authpro/vendor/geekcom/phpjasper/src/PHPJasper.php on line 93'

Parece que ele interpreta que o "string" na assinatura da função faz parte do namespace do PHPJasper, mas isso não tem nada a ver... Se tu tirar fora o type hinting das funções tudo funciona 100%.

Alguma ideia do que pode estar acontecendo?

**Comment by geekcom** [comment]
Olá @luisfwermann você poderia mostrar um trecho do seu código incluindo a linha 42, assim fica mais fácil ajudar com a questão.

**Comment by luisfwermann** [comment]
Sim @geekcom, segue abaixo:
<pre>
namespace Common\V1\Rest\JasperReport;

use PHPJasper\PHPJasper;
use ZF\Rest\AbstractResourceListener;

class JasperReportResource extends AbstractResourceListener
{
    public function fetchAll()
    {
        $jasper = new PHPJasper();

        $input = '/home/solis/JaspersoftWorkspace/MyReports/mais_teste.jasper';
        $output = '/home/solis/Downloads/jaspee';
        $options = [
            'format' =>
                ['pdf', 'rtf', 'xml'],
            'locale' => 'pt_BR',
            'db_connection' => [
                'driver' => 'postgres',
                'password' => 'postgres',
                'username' => 'postgres',
                'host' => 'localhost',
                'database' => 'authpro',
                'port' => '5432'
            ]
        ];
        $jasper->process(
            $input,
            $output,
            $options
        )->execute();




        return 'sucesso';
    }

}
</pre>

**Comment by geekcom** [comment]
Testei seu exemplo acima e não parece conter erro algum com relação a PHPJasper, inclusive "rodei" seu código em uma máquina Ubuntu.

**Comment by luisfwermann** [comment]
Eita! Erro meu aqui, instalei o PHP 7 mas não habilitei ele no Apache... ainda estava rodando com o PHP 5 habiltiado. Está resolvido, obrigado pela atenção!

**Comment by geekcom** [comment]
por nada, estamos aqui pra isso.
