### ISSUE TITLE
Resources in report

### ISSUE THREAD

**Issue by Azariil** [PHPJasper/phpjasper#99]
Hi. 
I use the image in the report for the logo.

```
<image>
        <reportElement x="10" y="10" width="50" height="50" uuid="6b170fd6-161e-40ff-ab0b-284c062091b2"/>
        <imageExpression><![CDATA["img/logo.png"]]></imageExpression>
</image>
```

But I had one problem. If I use only parameters in the report, the report is not generated, because the parameter "-r" is missing. This happens because in this code section this parameter is added only if there is a connection to the database or another resource.

```
if ($options['db_connection']) {
    ...
    if ($options['resources']) {
         $this->command .= " -r {$options['resources']}";
    }
}
```

I somehow incorrectly use this parameter? How can you add photos to the report differently?

Thanks!

**Comment by geekcom** [comment]
Hi @Azariil , i use images as parameter, see how to do...

**yourReport.jrxml**
```java
<parameter name="image" class="java.lang.String"/>

<image>
    <reportElement key="" x="7" y="2" width="69" height="76" uuid="3dd59614-b0b3-4034-a9c5-7a936d36e79a"/>
    <imageExpression><![CDATA[$P{image}]]></imageExpression>
</image>
```

**yourController.php**
```php
$input = '/home/geekcom/projects/project1/reports/yourReport.jrxml';
$output = '/tmp';
$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => [
        'image' => '/home/geekcom/projects/project1/public/images/image.png',
    ],
];

$jasper = new PHPJasper;
$jasper->process(
    $input,
    $output,
    $options
)->execute();

```

**Comment by geekcom** [comment]
Thanks for suggestion @Azariil see.. https://github.com/PHPJasper/phpjasper/pull/100

**Comment by Azariil** [comment]
Hi @geekcom 
Thank you very much for the last commit.
I just add an image in Jasper Studio and do not forward any parameters in the code. With the -r option, everything is perfectly generated.
Thank you.
